<?php
use Zend\Session\Container;
$logincontainer = new Container('credo');
?>
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Update Password<!--<small>Preview</small>--></h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('employee', array('action' => 'index')); ?>"> Employee</a></li>
        <li class="active">Change Password</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
<form class="form-horizontal" role="form" name="updatePasswordInformation" id="updatePasswordInformation"  method="post" action="<?php echo $this->url('employee', array('action' => 'change-password')); ?>" autocomplete="off" onsubmit="validateNow();
        return false;">
    <div class="form-group">
        <label for="typeName" class="col-lg-2 control-label">Current Password<span class="mandatory">*</span></label>
        <div class="col-lg-3">
            <input type="password" name="currentpassword" id="password" class="form-control isRequired" placeholder="Password"  title="Please enter your password" onblur="checkNameValidation('users','password', this, '<?php echo "employee_id##" . $logincontainer->employeeId; ?>', 'If your enter the current password is wrong.')"/>
        </div>
    </div>

    <div class="form-group">
        <label for="typeName" class="col-lg-2 control-label">New Password<span class="mandatory">*</span></label>
        <div class="col-lg-3">
            <input type="password" name="password" id="newpassword" class="form-control isRequired" placeholder="New Password"  title="Please enter your password" />
        </div>
    </div>

    <div class="form-group">
        <label for="typeName" class="col-lg-2 control-label">Confirm Password<span class="mandatory">*</span></label>
        <div class="col-lg-3">
            <input type="password" name="password" id="confirmpassword" class="form-control isRequired confirmPassword" placeholder="Confirm Password"  title=""/>
        </div>
    </div>


    <div class="box-footer">
            <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
            <a href="<?php echo $this->url('employee', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
        </div>
</form>
        </div>
    </div>
</section>
</div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'updatePasswordInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('updatePasswordInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg)
    {
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!='')
        {
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data == 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
        }
    }
</script>