<?php
$clientArray=array();
if(trim($result->monthly_bill_generated_client)!=""){
$clientArray=explode(",",$result->monthly_bill_generated_client);
}
?>
 <!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Edit </span>
				<span class="pageHeadingLabe12"> User</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('user', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
					<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                 <li><a href="<?php echo $this->url('user', array('action' => 'index')); ?>"> Users</a></li>
				<li class="active">Add User</li>
				</ol>
			</div>
		</div>
  </section>
<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="userInformation" id="userInformation"  method="post" action="<?php echo $this->url('user', array('action' => 'edit')); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="employee" class="col-lg-4 control-label">Employee <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" name="employee" id="employee" onchange="checkEmployeeName('users', 'employee_id', this,'<?php echo "user_id##" .$result->user_id; ?>', 'The selected employee already created user details. Please choose another employee.')"">
                                      <option value="">--Select--</option>
                                      <?php
                                      foreach($employee as $emp){
                                      ?>
                                      <option value="<?php echo $emp['employee_id']; ?>" <?php echo(($emp['employee_id']==$result->employee_id) ? "selected='selected'" : "") ?> data-employee-code="<?php echo $emp['employee_no']; ?>"><?php echo ucwords($emp['employee_name'])." - ".$emp['employee_no']; ?></option>
                                      <?php } ?>
                                    </select>
                                    <input type="hidden" class="form-control isRequired" id="employeeCode" name="employeeCode" value="<?php echo $result->employee_no; ?>"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="userName" class="col-lg-4 control-label">User Name <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="userName" name="userName" placeholder="Enter user name" title="Please enter user name" onblur="checkNameValidation('users', 'user_name', this,'<?php echo "user_id##" .$result->user_id; ?>', 'The user name that you entered already exist. Please enter another name.')" value="<?php echo $result->user_name; ?>"/>
                                    <input type="hidden" class="form-control isRequired" id="userId" name="userId"  value="<?php echo base64_encode($result->user_id); ?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="password" class="col-lg-4 control-label">Password </label>
                                <div class="col-lg-6">
                                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" title="Please enter password" />
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="email" class="col-lg-4 control-label">Email <span class="mandatory">*</span> </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired isEmail" id="email" name="email" placeholder="Enter Email" title="Please enter email" value="<?php echo $result->email; ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
					<div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="email" class="col-lg-4 control-label">Monthly Bill Generated Client </label>
                                <div class="col-lg-6">
                                    <select  class="form-control select2" id="client" name="client[]" title="Please select client" multiple="multiple">
                                        <option></option>
                                        <?php foreach($clientResult as $val){ ?>
										<option value="<?php echo $val['client_id']; ?>" <?php echo((in_array($val['client_id'],$clientArray)) ? "selected='selected'" : "") ?>><?php echo $val['client_name']; ?></option>
										<?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>	
					</div>
                    <fieldset>
                        <div class="form-group">
                                <label class="col-sm-2 control-label">Note:</label>
                                <div class="col-sm-10">
                                        <p class="form-control-static">Unless you choose "access" the people belonging to this role will not be able to access other rights like "add", "edit" etc.</p>
                                </div>
                        </div>
                        <div class="form-group" style="padding-left:138px;">
                        <strong>Select All</strong> <a style="color: #333;" href="javascript:void(0);" id="cekAllPrivileges"><input type='radio' class='layCek' name='cekUnCekAll'/> <i class='fa fa-check'></i></a>
                        &nbsp&nbsp&nbsp&nbsp<strong>Unselect All</strong> <a style="color: #333;" href="javascript:void(0);" id="unCekAllPrivileges"><input type='radio' class='layCek' name='cekUnCekAll'/> <i class='fa fa-times'></i></a>
                        </div>
                        <table class="table table-striped table-hover responsive-utilities jambo_table">
                        <?php
                        $role = $result->employee_no;
                        foreach ($resourceResult as $value) {
						echo "<tr class=''>";
						echo "<td><strong>" . ucwords($value['display_name']) . "</strong></td>";
						foreach ($value['privilege'] as $privilege) {
							if(isset($resourcePrivilegeMap[$role][$value['resource_id']][$privilege['privilege_name']]) && $resourcePrivilegeMap[$role][$value['resource_id']][$privilege['privilege_name']] == 'allow'){
								$allowChecked = " checked='' ";
                                        $denyChecked = "";
                            } else {
        
							$denyChecked = " checked='' ";
							$allowChecked = "";
							}
						echo "<td>". "<label class='labelName'>" . ucwords($privilege['display_name']) . "</label>
                                        
                                                                                        <label>
                                                                                                <input type='radio' class='cekAll layCek'  name='resource[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]" . "' value='allow' $allowChecked> <i class='fa fa-check'></i>
                                                                                        </label>
                                                                                        <label>
                                                                                                <input type='radio' class='unCekAll layCek'  name='resource[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]" . "' value='deny' $denyChecked>  <i class='fa fa-times'></i>
                                                                                        </label>
                                                                                                           
                                                                        </td>";
                                                }
                                                echo "</tr>";
                          }
                          ?>	
                        </table>
                        </fieldset>
                    
                    <div class="box-footer">
                        <a href="<?php echo $this->url('user', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
						<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'userInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('userInformation').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        $.blockUI();
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
                $("#employeeCode").val('');
                $.unblockUI();
            }
            else {
                duplicateName = true;
                $.unblockUI();
            }
        });
    }
    
    function checkEmployeeName(tableName, fieldName, obj, fnct, msg){
        $.blockUI();
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
                $("#employeeCode").val('');
                $.unblockUI();
            }
            else {
                duplicateName = true;
                selected=obj.options[obj.selectedIndex];
                objValue=selected.getAttribute('data-employee-code');
                $("#employeeCode").val(objValue);
                $.unblockUI();
            }
        });
    }
    
    $("#cekAllPrivileges").click(function() {
        $('.unCekAll').prop('checked', false);
        $('.cekAll').prop('checked', true);
    });

    $("#unCekAllPrivileges").click(function() {
		$('.cekAll').prop('checked', false);
        $('.unCekAll').prop('checked', true);
    });
	$(function() {
      $(".select2").select2({
        placeholder: "--Select--"
      });
	});
</script>