<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->employeeCode;
$acl=$this->layout()->acl;

$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
?>
<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" style="font-size:25px;">
				<span class="pageHeadingLabel1" >Manage </span>
				<span class="pageHeadingLabe12"> User</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<?php
					if ($acl->isAllowed($role, 'Admin\Controller\User', 'add')) {
					?>
					<a href="<?php echo $this->url('user',array('action' => 'add'));?>" class="btn btn-primary " style=""><i class="fa fa-plus"></i>&nbsp;Add User</a>
					<?php } ?>
				</span>
			</div>
		</div>
    </section>
	
    <!-- Main content -->
    <section class="content">
		<div class="row">
			<div class="col-xs-12">
					<table id="userDataTable" class="beecabsTable table">
						<thead>
							<tr>
								<th>Employee Name</th>
								<th>User Name</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td colspan="4" class="dataTables_empty">Loading data from server</td>
							</tr>
						</tbody>
					  </table>
				
				
			</div>
			<!-- /.col -->
		</div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
	
<script type="text/javascript">
    /* Table initialisation */
     oTable = null;
        $(document).ready(function() {
    $('#userDataTable').dataTable( {
		"bAutoWidth": false,
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		<?php echo $editAction;?>
            ],
		"aaSorting": [[ 0, "asc" ]],
        "sAjaxSource": "<?php echo $this->url('user',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
    } );

} );
       
</script>