	<!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Edit </span>
				<span class="pageHeadingLabe12"> Role</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('roles', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
					<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
        <li><a href="<?php echo $this->url('roles', array('action' => 'index')); ?>"> Roles</a></li>
        <li class="active">Edit Role</li>
				</ol>
			</div>
		</div>
  </section>
		
<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addRoleInformation" id="addRoleInformation"  method="post" action="<?php echo $this->url('roles', array('action' => 'edit')); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="roleName" class="col-lg-4 control-label">Role Name <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="roleName" name="roleName" placeholder="Enter role name" title="Please enter role name" onblur="checkNameValidation('roles', 'role_name', this,'<?php echo "role_id##" .$result->role_id; ?>', 'Already exist this role name . Please enter another name.');" value="<?php echo $result->role_name; ?>"/>
									<input type="hidden" class="form-control isRequired" id="roleId" name="roleId"  value="<?php echo base64_encode($result->role_id); ?>" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="roleCode" class="col-lg-4 control-label">Role Code <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="roleCode" name="roleCode" placeholder="Enter role code" title="Please enter role code" onblur="checkNameValidation('roles', 'role_code', this,'<?php echo "role_id##" .$result->role_id; ?>', 'Already exist this role code . Please enter another name.');" value="<?php echo $result->role_code; ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control" id="status" name="status" title="Please select source status">
                                        <option value="active" <?php echo(($result->status=='active') ? "selected='selected'" : "") ?>>Active</option>
                                        <option value="inactive" <?php echo(($result->status=='inactive') ? "selected='selected'" : "") ?>>Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                        
                    <div class="box-footer">
                        <a href="<?php echo $this->url('roles', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
												<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'addRoleInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('addRoleInformation').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
    
   
</script>
