<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->employeeCode;
$acl=$this->layout()->acl;
if ($acl->isAllowed($role, 'Admin\Controller\Roles', 'edit')) {
	$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
}else{
	$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" style="font-size:25px;">
				<span class="pageHeadingLabel1" >Manage </span>
				<span class="pageHeadingLabe12"> Role</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<?php
					if ($acl->isAllowed($role, 'Admin\Controller\Roles', 'add')) {
					?>
					<a href="<?php echo $this->url('roles',array('action' => 'add'));?>" class="btn btn-primary " style=""><i class="fa fa-plus"></i>&nbsp;Add Role</a>
					<?php } ?>
				</span>
			</div>
		</div>
    </section>
	
    <!-- Main content -->
    <section class="content">
		<div class="row">
			<div class="col-xs-12">
					<table id="roleDataTable" class="beecabsTable table">
						<thead>
							<tr>
								<th>Role Name</th>
								<th>Role Code</th>
								<th>Status</th>
								<?php
								if ($acl->isAllowed($role, 'Admin\Controller\Roles', 'edit')) {
								?>
								<th>Action</th>
								<?php } ?>
							</tr>
						</thead>
						<tbody>
							<tr>
								  <td colspan="8" class="dataTables_empty">Loading data from server</td>
							</tr>
						</tbody>
					  </table>
				
				
			</div>
			<!-- /.col -->
		</div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
	
<script type="text/javascript">
    /* Table initialisation */
     oTable = null;
        $(document).ready(function() {
		$('#roleDataTable').dataTable( {
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			 "aoColumns": [
			<?php echo $editAction;?>
				],
			"sAjaxSource": "<?php echo $this->url('roles',array('action' => 'index')); ?>",
			 "fnServerData": function ( sSource, aoData, fnCallback ) {
					$.ajax({
						"dataType": 'json',
						"type": "POST",
						"url": sSource,
						"data": aoData,
						"success": fnCallback
					});
				}
		} );
	} );
       
</script>