<?php
use Application\Service\CommonService;
$commonService=new CommonService();
if(isset($result['paid_date']) && trim($result['paid_date'])!=""){
$result['paid_date']=$commonService->humanDateFormat($result['paid_date']);
}
?>
<style>
    .help{
        font-size:11px;
    }
</style>
<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Edit </span>
				<span class="pageHeadingLabe12"> Booking</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('booking', array('action' => 'pending')); ?>" class="btn btn-default">Cancel</a>
                    <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                <li><a href="<?php echo $this->url('booking', array('action' => 'pending')); ?>">Pending Booking</a></li>
                <li class="active">Edit Booking</li>
				</ol>
			</div>
		</div>
    </section>

<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addBookingInformation" id="addBookingInformation"  method="post" action="<?php echo $this->url('booking', array('action' => 'edit')); ?>" autocomplete="off">
                <div class="box-body" style="padding:0 !important;">
                  <div class="row">
                    <div class="col-md-4 div-group -animated select-wrapper">
                      <label for="company">Company</label>
                      <select  class="form-control isRequired" id="company" name="company" title="Please select company" onchange="getClient();">
                          <option value="">-- Select Company --</option>
                          <?php
                          foreach($company as $val){
                          ?>
                          <option value="<?php echo $val['company_id']; ?>" <?php echo(($val['company_id']==$result['company_id']) ? "selected='selected'" : "") ?>><?php echo ucwords($val['company_name']);  ?></option>
                          <?php
                          }
                          ?>
                      </select>
                    </div>
                    <div class="col-md-4 div-group -animated select-wrapper">
                       <label for="businessUnit">Booking Type</label>
                        <select  class="form-control isRequired" id="businessUnit" name="businessUnit" title="Please select booking type" onchange="getBookingRef();checkBookingType();checkPaymentStatus();getClient();">
                            <option value="">-- Select Booking Type --</option>
                            <?php
                            foreach($businessUnitResult as $businessUnit){
                                if($businessUnit['unit_id']==2 || $businessUnit['unit_id']==4){
                            ?>
                            <option value="<?php echo $businessUnit['unit_id']; ?>" <?php echo(($businessUnit['unit_id']==$result['booking_type']) ? "selected='selected'" : "") ?>><?php echo ucwords($businessUnit['unit_name']);  ?></option>
                            <?php
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div class="col-md-4 div-group -animated select-wrapper" id="clientDiv">
                      <label for="client">Client</label>
                      <select  class="form-control isRequired" id="client" name="client" title="Please select client" onchange="getGuestDetails();getBookerDetails();">
                          <option value="">--Select Client--</option>
                      </select>
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="col-md-4 div-group -animated">
                      <label>Booking Ref.</label>
                      <input type="text" class="form-control isRequired" id="bookingRef" name="bookingRef" placeholder="Booking Ref." title="Please enter booking reference" value="<?php echo $result['booking_no']; ?>"/>
                      <input type="hidden" class="form-control" id="bookingCode" name="bookingCode" value="<?php echo $result['booking_code']; ?>"/>
                      <input type="hidden" class="form-control" id="bookingSortNo" name="bookingSortNo" value="<?php echo $result['booking_sort_key']; ?>"/>
                      <input type="hidden" class="form-control isRequired" id="bookingId" name="bookingId" value="<?php echo base64_encode($result['booking_id']); ?>"/>
                    </div>
                    
                    <div class=" col-md-4 div-group -animated select-wrapper">
                      <label for="city">City</label>
                      <select  class="form-control isRequired" id="city" name="city" title="Please select city" >
                          <option value="">-- Select Booking City --</option>
                          <?php
                          foreach($cityResult as $city){
                          ?>
                          <option value="<?php echo $city['city_id']; ?>" <?php echo(($city['city_id']==$result['city']) ? "selected='selected'" : "") ?>><?php echo ucwords($city['city_name']);  ?></option>
                          <?php
                          }
                          ?>
                      </select>
                    </div>
                    <div class="col-md-4 div-group -animated select-wrapper">
                      <label for="vehicleCategory">Vehicle Category</label>
                       <select  class="form-control isRequired" id="vehicleCategory" name="vehicleCategory" title="Please select vehicle category">
                            <option value="">-- Select Vehicle Category --</option>
                            <?php
                            foreach($vehicleMakeTypeResult as $vehicleMakeType){
                            ?>
                            <option value="<?php echo $vehicleMakeType['make_id']; ?>" <?php echo(($vehicleMakeType['make_id']==$result['make_type']) ? "selected='selected'" : "") ?>><?php echo ucwords($vehicleMakeType['make_type']);  ?></option>
                            <?php
                            }
                            ?>
                        </select>
                    </div>
                  </div>
                    
                    <div class="row">
						<div class="col-md-4 div-group -animated select-wrapper">
							<label for="vehicleType">Vehicle Make Type</label>
							<select  class="form-control isRequired" id="vehicleType" name="vehicleType" title="Please select vehicle type" >
									<option value="">--Select Vehicle Make Type--</option>
									<?php
									foreach($vehicleType as $val){
									?>
									<option value="<?php echo base64_encode($val['type_id']); ?>" <?php echo(($result['vehicle_type']==$val['type_id']) ? "selected='selected'" : "") ?>><?php echo $val['type_name'];  ?></option>
									<?php
									}
									?>
							</select>
						</div>
                      <div class="col-md-4 div-group -animated select-wrapper">
                        <label for="dutyType">Duty Type</label>
                        <select  class="form-control isRequired" id="dutyType" name="dutyType" title="Please select duty type">
                            <option value="">-- Select Duty Type --</option>
                            <?php
                            foreach($rentalTypeResult as $rentalType){
                            ?>
                            <option value="<?php echo $rentalType['type_id']; ?>" <?php echo(($rentalType['type_id']==$result['duty_type']) ? "selected='selected'" : "") ?>><?php echo ucwords($rentalType['type_name']);  ?></option>
                            <?php
                            }
                            ?>
                        </select>
                      </div>
                    <div class=" col-md-1 div-group -animated select-wrapper">
                      <label for="guestTitle">Title</label>
                       <select class="form-control" id="guestTitle" name="guestTitle">
                            <option value="Mr">Mr</option>
                            <option value="Ms">Ms</option>
                            <option value="Dr">Dr</option>
                            <option value="Capt">Capt</option>
                        </select>
                    </div>
                    <div class="col-md-3 div-group -animated select-wrapper">
                        <label for="customerName">Customer Name</label>
                        <select  class="form-control isRequired" id="customerName" name="customerName" title="Please select customer">
                            <option value="">--Select--</option>
                        </select>
                    </div>
                    </div>
                    
                    <div class="row">
						<div class=" col-md-4 div-group -animated">
                        <label for="customerMobileNo">Customer Mobile No.</label>
                        <input type="text" class="form-control isRequired" id="customerMobileNo" name="customerMobileNo" title="Please enter the customer mobile number" value="<?php echo $result['guest_mobile_no']; ?>"/>
                        <input type="hidden" class="form-control" id="customerId" name="customerId" value="<?php echo $result['guest_id']; ?>"/>
                        <div class="help">( Please enter comma separated mutiple mobile number eg. 9025048816,819089422)</div>
						</div>
                      <div class=" col-md-4 div-group -animated">
                        <label>Trip Date</label>
                        <input type="text" class="form-control isRequired datepicker readonly" id="tripDate" name="tripDate" title="Please select the trip date" readonly="readonly" value="<?php echo $commonService->humanDateFormat($result['trip_from_date']); ?>"/>
                      </div>
                      <div class="col-md-4 div-group -animated select-wrapper">
                        <label for="tripTime">Trip Time</label>
                        <select class="form-control isRequired select2" id="tripTime" name="tripTime" title="Please selelct trip time">
                            <option value="">--Select Trip Time--</option>
                            <?php
                            for($t=0;$t<=23;$t++){
                                if(strlen($t)==1){
                                    $t="0".$t;
                                }
                            ?>
                            <option value="<?php echo $t.":00"; ?>" <?php echo(($result['trip_start_time']== $t.":00") ? "selected='selected'" : "") ?>><?php echo $t.":00"; ?></option>
                            <option value="<?php echo $t.":15"; ?>" <?php echo(($result['trip_start_time']== $t.":15") ? "selected='selected'" : "") ?>><?php echo $t.":15"; ?></option>
                            <option value="<?php echo $t.":30"; ?>" <?php echo(($result['trip_start_time']== $t.":30") ? "selected='selected'" : "") ?>><?php echo $t.":30"; ?></option>
                            <option value="<?php echo $t.":45"; ?>" <?php echo(($result['trip_start_time']== $t.":45") ? "selected='selected'" : "") ?>><?php echo $t.":45"; ?></option>
                            <?php
                              }
                            ?>
                        </select>
                      </div>
                        
                    </div>
                    
                    <div class="row">
						<div class="col-md-4 div-group -animated select-wrapper">
                        <label>Booker Name</label>
                        <select  class="form-control isRequired" id="bookerName" name="bookerName" title="Please select booker name">
                          <option value="">--Select--</option>
                        </select>
                        </div>
                    <div class=" col-md-4 div-group -animated">
                      <label>Booker Mobile No.</label>
                      <input type="text" class="form-control isRequired" id="bookerMobileNo" name="bookerMobileNo" title="Please enter the booker mobile number" value="<?php echo $result['booker_mobile_no']; ?>"/>
                      <div class="help">( Please enter comma separated mutiple mobile number eg. 9025048816,819089422)</div>
                    </div>
                    <div class=" col-md-4 div-group -animated">
                      <label for="bookerMailId">Booker Mail Id</label>
                      <input type="text" id="bookerMailId" name="bookerMailId" class="form-control" value="<?php echo $result['booker_email']; ?>"/>
                      <input type="hidden" id="bookerId" name="bookerId" class="form-control" value="<?php echo $result['booker_id']; ?>"/>
                      <div class="help">( Please enter comma separated mutiple email eg. ilahir@gmail.com,booking@beecabs.in)</div>
                    </div>
                    </div>
                            
                    <div class="row">
						<div class="col-md-4 div-group -animated">
						<label>Pickup Area</label>
						<input type="text" class="form-control isRequired" id="pickupArea" name="pickupArea" title="Please enter pickup area" value="<?php echo $result['pickup_area']; ?>"/>
						</div>
                        <div class=" col-md-4 div-group -animated">
                        <label for="pickupAddress">Pickup Address</label>
                        <textarea id="pickupAddress" name="pickupAddress" class="form-control isRequired" title="Please enter the pickup address"><?php echo $result['pickup_address']; ?></textarea>
                        </div>
                      <div class="col-md-4 div-group -animated">
                        <label for="specialIns">Special Instruction</label>
                        <textarea id="specialIns" name="specialIns" class="form-control"><?php echo $result['spec_ins']; ?></textarea>
                      </div>
                      
                    </div>
                    
                    <div class="row">
						<div class=" col-md-4 div-group -animated select-wrapper">
						<label for="paymentStatus">Payment Mode</label>
                        <select class="form-control isRequired" id="paymentMode" name="paymentMode" title="Please select payment mode">
                            <option value="">--Select Payment Mode--</option>
                            <?php
                            foreach($paymentMode as $mode){
                            ?>
                            <option value="<?php echo base64_encode($mode['type_id']); ?>" <?php echo(($mode['type_id']==$result['mop']) ? "selected='selected'" : "") ?>><?php echo $mode['payment_type']; ?></option>
                            <?php
                            }
                            ?>
                        </select>
						</div>
                        <div class=" col-md-4 div-group -animated select-wrapper" id="paymentStatusDiv">
                        <label for="paymentStatus">Payment Status</label>
                         <select class="form-control" id="paymentStatus" name="paymentStatus" title="Please select payment status" onchange="checkPaymentStatus();">
                              <option value="">--Select Payment Status--</option>
                              <option value="pending" <?php echo(($result['payment_status']=='pending') ? "selected='selected'" : "") ?>>Pending</option>
                              <option value="paid" <?php echo(($result['payment_status']=='paid') ? "selected='selected'" : "") ?>>Paid</option>
                          </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class=" col-md-4 div-group -animated" id="paidDateDiv">
                           <label>Paid Date</label>
                          <input type="text" class="form-control datepicker readonly" id="paidDate" name="paidDate" title="Please select the paid date" readonly="readonly" value="<?php echo $result['paid_date']; ?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class=" col-md-4 ">
                            <div class="checkbox">
                              <label>
                                <input type="checkbox" name="sendEmail" id="sendEmail" checked="checked">
                                Send booking Email
                              </label>
                            </div>
                        </div>
                    </div>
            </div>
                <div class="box-footer">
                    <a href="<?php echo $this->url('booking', array('action' => 'pending')); ?>" class="btn btn-default">Cancel</a>
                    <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script src="<?php echo $this->basePath() . '/assets/js/bootstrap-typeahead.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/animate-label.js'; ?>"></script>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addBookingInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('addBookingInformation').submit();
            }
        }
    }
    
  $(function() {
      
		$('.datepicker').datepicker({
        //todayBtn: "linked",
        clearBtn: true,
        autoclose: true,
        todayHighlight: true,
        format: 'dd-M-yyyy'
		}).on('changeDate', function(e) {
       $(this).parent('.div-group').addClass('-active');
    });
    
    $(".select2").select2({
        placeholder: "--Trip Time--"
    });
   
    
    
    
      if ($('.div-group .-animated .form-control').val() != '') {
        //$('.div-group input').parent('.div-group').addClass('-active');
        $('.div-group .form-control').parent('.div-group').addClass('-active');
        
      } else {
        $(this).parent('.div-group').removeClass('-active');
      }
      if('<?php echo $result['booking_type']; ?>'==2){
        getClientOnload();  
      }
      
      checkBookingType();
      checkPaymentStatus();
	});
    
    function getClient(){
        company=$("#company").val();
        if(company!=""){
            $.blockUI();
            $.post("<?php echo $this->url('clients', array('action' => 'get-client-by-company')); ?>", {company:company},
            function(data){
                if (data!="") {
                    document.getElementById("client").innerHTML=data;
                }
                $.unblockUI();
            });
        }
    }
    
    function getBookingRef(){
        businessUnit=$("#businessUnit").val();
        if(businessUnit==2){
            $.blockUI();
            $.post("<?php echo $this->url('booking', array('action' => 'get-corporate-booking-no')); ?>",
            function(data){
                if (data!="") {
                    splStr=data.split("#");
                    $("#bookingRef").val(splStr[0]+splStr[1]);
                    $("#bookingCode").val(splStr[0]);
                    $("#bookingSortNo").val(splStr[1]);
                }
                $.unblockUI();
            });
        }else{
            $("#bookingRef").val('');
            $("#bookingCode").val('');
            $("#bookingSortNo").val('');
        }
    }
    
    function getClientOnload(){
        company=$("#company").val();
        if(company!=""){
            $.blockUI();
            $.post("<?php echo $this->url('clients', array('action' => 'get-client-by-company')); ?>", {company:company},
            function(data){
                if (data!="") {
                    document.getElementById("client").innerHTML=data;
                    $("#client").val('<?php echo $result['client_id']; ?>');
                    getGuestDetailsOnload();
                    getBookerDetailsOnload();
                }
                $.unblockUI();
            });
        }
    }

    function getGuestDetails(){
        clientId=$('#client').val();
        $.post("<?php echo $this->url('clients', array('action' => 'get-guest-list')); ?>", {clientId:clientId},
		function(data){
		    if(data!="")
		    {
                document.getElementById("customerName").innerHTML=data;
                $("#customerName").select2({
                    placeholder: "--Select Customer--",
                    tags: true
                }).on("change", function(e) {
                    //console.log($(this).val());
                    customer=$('#customerName').select2('data');
                    selected=this.options[this.selectedIndex];
                    guestMobile=selected.getAttribute('data-mobile');
                    guestId=selected.getAttribute('data-id');
                    $("#customerMobileNo").val(guestMobile);
                    $("#customerId").val(guestId);
                    if($("#customerMobileNo").val()!=""){
                        $("#customerMobileNo").parent('.div-group').addClass('-active');    
                    }
                });
		    }
		   
		});
    }
    
    function getBookerDetails() {
        $.blockUI();
        clientId=$('#client').val();
        $.post("<?php echo $this->url('clients', array('action' => 'get-contact-list')); ?>", { clientId : clientId},
		function(data){
		    if(data!="")
		    {
                document.getElementById("bookerName").innerHTML=data;
                $("#bookerName").select2({
                    placeholder: "--Select Booker--",
                    tags: true
                }).on("change", function(e) {
                    //console.log($(this).val());
                    selected=this.options[this.selectedIndex];
                    bookerMobile=selected.getAttribute('data-mobile');
                    bookerEmail=selected.getAttribute('data-email');
                    bookerId=selected.getAttribute('data-id');
                    $("#bookerMobileNo").val(bookerMobile);
                    $("#bookerMailId").val(bookerEmail);
                    $("#bookerId").val(bookerId);
                    if($("#bookerMobileNo").val()!=""){
                        $("#bookerMobileNo").parent('.div-group').addClass('-active');    
                    }
                    if($("#bookerMailId").val()!=""){
                        $("#bookerMailId").parent('.div-group').addClass('-active');    
                    }
                });
		    }
            $.unblockUI();
		});
    }
    
    function getGuestDetailsOnload(){
        clientId=$('#client').val();
        $.post("<?php echo $this->url('clients', array('action' => 'get-guest-list')); ?>", {clientId:clientId},
		function(data){
		    if(data!="")
		    {
                document.getElementById("customerName").innerHTML=data;
                $("#customerName").val('<?php echo $result['guest_name']; ?>');
                $("#customerName").select2({
                    placeholder: "--Select Customer--",
                    tags: true
                }).on("change", function(e) {
                    //console.log($(this).val());
                    customer=$('#customerName').select2('data');
                    selected=this.options[this.selectedIndex];
                    guestMobile=selected.getAttribute('data-mobile');
                    guestId=selected.getAttribute('data-id');
                    $("#customerMobileNo").val(guestMobile);
                    $("#customerId").val(guestId);
                    if($("#customerMobileNo").val()!=""){
                        $("#customerMobileNo").parent('.div-group').addClass('-active');    
                    }
                });
		    }
		   
		});
    }
    
    function getBookerDetailsOnload() {
        $.blockUI();
        clientId=$('#client').val();
        $.post("<?php echo $this->url('clients', array('action' => 'get-contact-list')); ?>", { clientId : clientId},
		function(data){
		    if(data!="")
		    {
                document.getElementById("bookerName").innerHTML=data;
                $("#bookerName").val('<?php echo $result['booker_name']; ?>');
                $("#bookerName").select2({
                    placeholder: "--Select Booker--",
                    tags: true
                }).on("change", function(e) {
                    //console.log($(this).val());
                    selected=this.options[this.selectedIndex];
                    bookerMobile=selected.getAttribute('data-mobile');
                    bookerEmail=selected.getAttribute('data-email');
                    bookerId=selected.getAttribute('data-id');
                    $("#bookerMobileNo").val(bookerMobile);
                    $("#bookerMailId").val(bookerEmail);
                    $("#bookerId").val(bookerId);
                    if($("#bookerMobileNo").val()!=""){
                        $("#bookerMobileNo").parent('.div-group').addClass('-active');    
                    }
                    if($("#bookerMailId").val()!=""){
                        $("#bookerMailId").parent('.div-group').addClass('-active');    
                    }
                });
		    }
            $.unblockUI();
		});
    }
    
    function checkBookingType(){
        businessUnit=$("#businessUnit").val();
        if(businessUnit==2){
            $("#paymentStatusDiv").css('display','none');
            $("#paymentStatus").val('pending');
        }else if(businessUnit==4){
            $("#paymentStatusDiv").css('display','block');
            
        }
    }
    
    function checkPaymentStatus(){
        payment_status=$("#paymentStatus").val();
        businessUnit=$("#businessUnit").val();
        if(payment_status=='paid' && businessUnit==4){
            $("#paidDateDiv").css('display','block');
            $("#paidDate").addClass('isRequired');
        }else{
            $("#paidDateDiv").css('display','none');
            $("#paidDate").val('');
            $("#paidDate").removeClass('isRequired');
        }
    }
</script>