<!-- Main content -->
<div class="content-wrapper">
     <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>View Vehicle Usage</h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('vehicle-usage', array('action' => 'index')); ?>"> Vehicle Usage</a></li>
        <li class="active">View Vehicle Usage</li>
      </ol>
    </section>
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal">
                <div class="box-body">
					<table class="table table-striped table-bordered table-condensed" align="center" style="width: 70%;">
						<thead>
                        <tr>
                            <th colspan="2" style="text-align: center;" class="bg-aqua">Vehicle Usage Details</th>
                        </tr>
                        </thead>
						<tr>
							<th style="width: 20%;">Vehicle Number</th>
							<td><?php echo $result->vehicle_no; ?></td>
						</tr>
						<tr>
							<th>Vehicle Type</th>
							<td><?php echo $result->type_name; ?></td>
						</tr>
						<tr>
							<th>Vehicle Usage Month</th>
							<td><?php echo $result->month."-".$result->year; ?></td>
						</tr>
						<tr>
							<th>Odometer Opening Kms</th>
							<td><?php echo $result->odometer_open_km; ?></td>
						</tr>
						<tr>
							<th>Odometer Closing Kms</th>
							<td><?php echo $result->odometer_close_km; ?></td>
						</tr>
						<tr>
							<th>Total Used Kms</th>
							<td><?php echo $result->total_used_km; ?></td>
						</tr>
						<tr>
							<th>Gps Used Kms</th>
							<td><?php echo $result->gps_used_km; ?></td>
						</tr>
						<tr>
							<th>Total Hotel Revenue  Kms</th>
							<td><?php echo $result->total_hotel_revenue_kms;; ?></td>
						</tr>
						<tr>
							<th>Total Corp Revenue Kms</th>
							<td><?php echo $result->total_corp_revenue_kms;; ?></td>
						</tr>
						<tr>
							<th>Non Revenue Kms</th>
							<td><?php echo $result->non_revenue_kms; ?></td>
						</tr>
						<tr>
							<th>Total Hotel Revenue</th>
							<td><?php echo $result->total_hotel_revenue; ?></td>
						</tr>
						<tr>
							<th>Total Corp Revenue</th>
							<td><?php echo $result->total_corp_revenue; ?></td>
						</tr>
						<tr>
							<th>Hotel Revenue Per Km</th>
							<td><?php echo $result->hotel_revenue_per_km; ?></td>
						</tr>
						<tr>
							<th>Corp Revenue Per Km</th>
							<td><?php echo $result->corp_revenue_per_km; ?></td>
						</tr>
						<tr>
							<th>Total Fuel</th>
							<td><?php echo $result->total_fuel; ?></td>
						</tr>
						<tr>
							<th>Fuel Amount</th>
							<td><?php echo $result->fuel_amount; ?></td>
						</tr>
						<tr>
							<th>Mileage Per Litre</th>
							<td><?php echo $result->mileage_per_litre; ?></td>
						</tr>
					</table>
					<br/>
					
                    <div class="box-footer">
                        <a href="<?php echo $this->url('vehicle-usage', array('action' => 'index')); ?>" class="btn btn-default">Back</a>
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->
    </div>

<script type="text/javascript">
    
   
</script>
