<!-- Main content -->
<div class="content-wrapper"> 
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
            <h1 style="color:red;" align="center">Sorry.You are not allowed to access this page.</h1>
            <h4 align="center">Please contact your system administrator for further assistance</h4>
            </div><!-- /.box-header -->
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->
</div>
