<!-- Main content -->
<div class="content-wrapper">
     <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>Add Company</h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('company', array('action' => 'index')); ?>"> Company</a></li>
        <li class="active">Add Company</li>
      </ol>
    </section>
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addCompanyInformation" id="addCompanyInformation"  method="post" action="<?php echo $this->url('company', array('action' => 'add')); ?>" enctype="multipart/form-data" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="companyName" class="col-lg-4 control-label">Company Name <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="companyName" name="companyName" placeholder="Enter company name" title="Please enter company name" onblur="checkNameValidation('company_details', 'company_name', this, null, 'Already exist this company name . Please enter another name.');"/>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="phoneNo" class="col-lg-4 control-label">Phone No</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="phoneNo" name="phoneNo" placeholder="Enter phone number" title="Please enter phone number"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="panNo" class="col-lg-4 control-label">Pan No <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="panNo" name="panNo" placeholder="Enter pan number" title="Please enter pan number"/>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTaxNo" class="col-lg-4 control-label">Service Tax No <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="serviceTaxNo" name="serviceTaxNo" placeholder="Enter service tax number" title="Please enter service tax number"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="sacNo" class="col-lg-4 control-label">SAC No <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="sacNo" name="sacNo" placeholder="Enter SAC number" title="Please enter SAC number"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="address" class="col-lg-4 control-label">Address <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <textarea class="form-control isRequired" name="address" id="address" placeholder="Address" title="Please enter the address"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                              <label for="city" class="col-lg-4 control-label">City <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired" id="city" name="city" placeholder="Enter city" title="Please enter city"/>
                              </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                              <label for="pincode" class="col-lg-4 control-label">Pincode <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired" id="pincode" name="pincode" placeholder="Enter pincode" title="Please enter pincode"/>
                              </div>
                          </div>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control" id="status" name="status" title="Please select status">
                                        <option value="active">Active</option>
                                        <option value="inactive">Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h4>Upload Company Documents</h4>
                    <table id="documentTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>Document Name</th>
                            <th>Attach File</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                            <input type="text" id="documentName1" name="documentName[]" class="form-control" placeholder="Enter document name" title="Please enter the document name"/>
                            </td>
                            <td>
                            <input type="file" class="form-control" title="please choose file" name="file[]" id="file1">
                            </td>
                            <td align="center">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                            </td>
                            
                        </tr>
                        </tbody>
                    </table>
                    <!--
                    <h4>Branch Details</h4>
                    <table id="branchTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>City <span class="mandatory">*</span></th>
                            <th>Phone No <span class="mandatory">*</span></th>
                            <th>Alt. Phone No</th>
                            <th>Address <span class="mandatory">*</span> </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                            <input type="text" id="city1" name="city[]" class="form-control isRequired" placeholder="City" title="Please enter the city"/>
                            </td>
                            <td>
                            <input type="text" class="form-control isRequired" id="phoneNo1" name="phoneNo[]" placeholder="Phone No" title="Please enter the phone number"/>
                            </td>
                            <td><input type="text" class="form-control" id="altPhoneNo1" name="altPhoneNo[]" placeholder="Alt. Phone No" title="Please enter the alternate phone number"/></td>
                            <td>
                            <textarea class="form-control isRequired" name="address[]" id="address1" placeholder="Address" title="Please enter the address"></textarea>
                            </td>
                            <td align="center">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                            </td>
                            
                        </tr>
                        </tbody>
                    </table>
                    -->
                    <div class="box-footer">
                        <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                        <a href="<?php echo $this->url('company', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->
    </div>

<script type="text/javascript">
    duplicateName = true;
    rowCount=1;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addCompanyInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('addCompanyInformation').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
    
    function insRow() {
		rowCount++;
		rl = document.getElementById("documentTable").rows.length;
		var a = document.getElementById("documentTable").insertRow(rl);
		a.setAttribute("style", "display:none;");
		a.setAttribute("class", "data");
		var b = a.insertCell(0);
		var c = a.insertCell(1);
		var d = a.insertCell(2);
		
		d.setAttribute("align", "center");
		
		rl = document.getElementById("documentTable").rows.length - 1;
		b.innerHTML = '<input type="text" class="form-control" id="documentName' + rowCount + '" name="documentName[]" placeholder="Enter document name" title="Please enter the document name"/>';
		c.innerHTML = '<input type="file" class="form-control" title="please choose file" name="file[]" id="file'+rowCount+'">';
		d.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
		$(a).fadeIn(800);
    }
	
	function removeRow(el) {
		$(el).fadeOut("slow", function() {
		    el.parentNode.removeChild(el);
		    rl = document.getElementById("documentTable").rows.length;
		    if (rl == 1) {
			insRow();
		    }
		});
    }
    
</script>
