<?php
//\Zend\Debug\Debug::dump($result['company']['company_id']);die;
$pathname = UPLOAD_PATH . DIRECTORY_SEPARATOR . "company" . DIRECTORY_SEPARATOR .$result['company']['company_id'];
?>
	<section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" style="font-size:25px;">
				<span class="pageHeadingLabel1" >View </span>
				<span class="pageHeadingLabe12"> Company</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('company', array('action' => 'index')); ?>" class="btn btn-default">Back</a>
				</span>
			</div>
		</div>
  </section>
  
<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal">
                <div class="box-body">
					<table class="table table-striped table-bordered table-condensed" align="center" style="width: 70%;">
						<thead>
                        <tr>
                            <th colspan="2" style="text-align: center;" class="bg-aqua">Company Details</th>
                        </tr>
                        </thead>
						<tr>
							<th style="width: 20%;">Company Name</th>
							<td><?php echo $result['company']['company_name']; ?></td>
						</tr>
						<tr>
							<th>Phone No</th>
							<td><?php echo $result['company']['phone_no']; ?></td>
						</tr>
						<tr>
							<th>Pan No</th>
							<td><?php echo $result['company']['pan_no']; ?></td>
						</tr>
						<tr>
							<th>GST No </th>
							<td><?php echo $result['company']['gst_no']; ?></td>
						</tr>
						<tr>
							<th>Address</th>
							<td><?php echo $result['company']['address']; ?></td>
						</tr>
						<tr>
							<th>City</th>
							<td><?php echo $result['company']['city']; ?></td>
						</tr>
						<tr>
							<th>Pincode</th>
							<td><?php echo $result['company']['pin_code']; ?></td>
						</tr>
						<tr>
							<th>Status</th>
							<td><?php echo ucwords($result['company']['status']); ?></td>
						</tr>
					</table>
                    
					<br/>
                    <table id="documentTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" align="center" style="width: 70%;">
                        <thead>
							<tr>
								<th colspan="2" style="text-align: center;" class="bg-aqua">Document Details</th>
							</tr>
                        <tr>
                            <th style="width: 20%;">Document Name</th>
                            <th>Attach File</th>
                            
                        </tr>
                        </thead>
                        <tbody>
							<?php
							$i=1;
							if(sizeof($result['document'])>0){
								foreach($result['document'] as $document){
							?>
							<tr>
								<td>
								<?php echo $document['document_name']; ?>
								</td>
								<td>
									<?php
										if(isset($document['file_name']) && trim($document['file_name'])!="" && file_exists($pathname. DIRECTORY_SEPARATOR.$document['file_name'])){
									?>
									<div class="form-control">
										<a target='_blank' href="<?php echo $this->basePath(). DIRECTORY_SEPARATOR."uploads". DIRECTORY_SEPARATOR."company". DIRECTORY_SEPARATOR .$result['company']['company_id']. DIRECTORY_SEPARATOR.$document['file_name'] ?>" ><?php echo $document['file_name']; ?></a>
									</div>
									<?php } ?>
								</td>
							</tr>
						<?php
							$i++;
								}
							}else{
						?>
						<tr>
                            <td colspan="2" style="text-align: center;">
							No data available
                            </td> 
                        </tr>
						<?php
							}
						?>
                        </tbody>
                    </table>
                    
                    <div class="box-footer">
                        <a href="<?php echo $this->url('company', array('action' => 'index')); ?>" class="btn btn-default">Back</a>
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
   
</script>
