<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->employeeCode;
$acl=$this->layout()->acl;
if ($acl->isAllowed($role, 'Admin\Controller\VehicleService', 'edit')) {
$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
$editCompleteWorkAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
}else{
$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
$editCompleteWorkAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" style="font-size:25px;">
				<span class="pageHeadingLabel1" >Manage </span>
				<span class="pageHeadingLabe12"> Vehicle Service</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<?php
					if ($acl->isAllowed($role, 'Admin\Controller\VehicleService', 'add')) {
					?>
					<a href="<?php echo $this->url('vehicle-service',array('action' => 'add'));?>" class="btn btn-primary " style=""><i class="fa fa-plus"></i>&nbsp;Add Service</a>
					<?php } ?>
				</span>
			</div>
		</div>
    </section>
	
    <!-- Main content -->
    <section class="content">
		<div class="row">
			<div class="col-xs-12">
					<div class="nav-tabs-custom">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#pendingWorkOrder" data-toggle="tab">Pending Work Order</a></li>
							<li><a href="#completedWorkOrder" data-toggle="tab">Completed Work Order</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="pendingWorkOrder">
								<table id="pendingServiceDataTable" class="beecabsTable table">
									<thead>
										<tr>
											<th>Work Order No</th>
											<th>Vehicle No</th>
											<th>Garage Name</th>
											<th>Garage In Date</th>
											<th>Garage In Kms</th>
											<th>Status</th>
											<?php if ($acl->isAllowed($role, 'Admin\Controller\VehicleService', 'edit')) { ?>
											<th>Action</th>
											<?php } ?>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="7" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>
							</div>
							<div class="tab-pane" id="completedWorkOrder">
								<form class="form-inline searchBox" style="margin-top:5px;">
									<div class="form-group">
									  <label>Search Garage In Date &nbsp;</label>
									  <input type="text" class="form-control" id="searchDate" name="searchDate" placeholder="Search Garage In Date" readonly="readonly"/>
									</div>
									<div class="form-group">
									<input type="button" onclick="javascript:cTable.fnDraw();" value="Search" class="btn btn-default">
									&nbsp;<a href="" class="btn btn-danger">Reset</a>
									&nbsp;<a href="javascript:void(0)" onclick="exportToExcel();" class="btn btn-primary" title="Download"><i class="fa fa-download"> Export to excel </i></a>
									</div>
								</form>
								<br/>
								<table id="serviceDataTable" class="beecabsTable table">
									<thead>
										<tr>
											<th>Work Order No</th>
											<th>Vehicle No</th>
											<th>Garage Name</th>
											<th>Garage In Date</th>
											<th>Garage In Kms</th>
											<th>Next Service Km</th>
											<th>Bill Amount</th>
											<th>Payment Status</th>
											<?php if ($acl->isAllowed($role, 'Admin\Controller\VehicleService', 'edit') || $acl->isAllowed($role, 'Admin\Controller\VehicleService', 'view')) { ?>
											<th style="width:110px;">Action</th>
											<?php } ?>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="9" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>	
			</div>
			<!-- /.col -->
		</div>
      <!-- /.row -->
	</section>
    <!-- /.content -->
<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    cTable = null;
	startDate="";
	endDate="";
    $(document).ready(function() {
		oTable=$('#pendingServiceDataTable').dataTable({
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			 "aoColumns": [
			<?php echo $editAction;?>
				],
			"aaSorting": [[3, "desc"]],
			"sAjaxSource": "<?php echo $this->url('vehicle-service',array('action' => 'pending-work-order')); ?>",
			 "fnServerData": function ( sSource, aoData, fnCallback ) {
					$.ajax({
						"dataType": 'json',
						"type": "POST",
						"url": sSource,
						"data": aoData,
						"success": fnCallback
					});
				}
		});
		
		cTable=$('#serviceDataTable').dataTable({
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			"aoColumns": [
			<?php echo $editCompleteWorkAction;?>
            ],
			"aaSorting": [[3, "desc"]],
			"sAjaxSource": "<?php echo $this->url('vehicle-service',array('action' => 'index')); ?>",
			"fnServerData": function ( sSource, aoData, fnCallback ) {
				aoData.push({ "name":"startDate","value": startDate});
				aoData.push({ "name":"endDate","value": endDate});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
		});
		
		$('#searchDate').daterangepicker({
		  format: 'DD-MMM-YYYY',
		  separator: ' to ',
		  startDate: moment().subtract('days', 29),
		  endDate: moment(),
		  ranges: {
			  'This Month': [moment().startOf('month'), moment().endOf('month')],
			  'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
		  }
		},
		function(start, end) {
		startDate = start.format('YYYY-MM-DD');
		endDate = end.format('YYYY-MM-DD');
		cTable.fnDraw();
		});
	});
	
	function exportToExcel(){
		$.blockUI();
		$.post("<?php echo $this->url('vehicle-service',array('action'=>'export-complete-work-order-to-excel')); ?>",{startDate:startDate,endDate:endDate},
			function(data){
			if(data == "" || data == null || data == undefined){
			$.unblockUI();
			alert('Unable to generate');
			}else{
			$.unblockUI();
			document.location.href = '/temporary/'+data;
			}
		});
	}
	
	function deleteVendorPayment(serviceId) {
        conf=confirm("Are you sure you want to delete this service");
		if (conf) {
			$.blockUI();
			$.post("<?php echo $this->url('vehicle-service',array('action' => 'delete')); ?>", {serviceId:serviceId},
			function(data){
				if (data>0) {
					alert("Deleted successfully");
					location="";
				}
				$.unblockUI();
			});
		}
    }
</script>
