<?php
use Application\Service\CommonService;
$commonService=new CommonService();
if(isset($result->payment_date) && trim($result->payment_date)!=""){
  $result->payment_date=$commonService->humanDateFormat($result->payment_date);
}
if(isset($result->insurance_paid_date) && trim($result->insurance_paid_date)!=""){
  $result->insurance_paid_date=$commonService->humanDateFormat($result->insurance_paid_date);
}
if(isset($result->garage_in_date) && trim($result->garage_in_date)!=""){
  $result->garage_in_date=$commonService->humanDateFormat($result->garage_in_date);
}
$pathname = UPLOAD_PATH . DIRECTORY_SEPARATOR . "vehicle-service" . DIRECTORY_SEPARATOR .$result->service_id;
?>
<!-- Main content -->
<div class="content-wrapper">
     <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>View Vehicle Service</h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('vehicle-service', array('action' => 'index')); ?>"> Vehicle Service</a></li>
        <li class="active">View Vehicle Service</li>
      </ol>
    </section>
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal">
                <div class="box-body">
                  <table class="table table-striped table-bordered table-condensed" align="center" style="width: 70%;">
                    <thead>
                      <tr>
                          <th colspan="2" style="text-align: center;" class="bg-aqua">Vehicle Service Details</th>
                      </tr>
                    </thead>
                    <tr>
                      <th style="width: 20%;">Work Order Number</th>
                      <td><?php echo $result->work_order_no; ?></td>
                    </tr>
                    <tr>
                      <th>Vehicle </th>
                      <td><?php echo $result->vehicle_no; ?></td>
                    </tr>
                    <tr>
                      <th>Garage Name </th>
                      <td><?php echo $result->garage_name; ?></td>
                    </tr>
                    <tr>
                      <th>Garage In Date </th>
                      <td><?php echo $result->garage_in_date; ?></td>
                    </tr>
                    <tr>
                      <th>Garage In Km </th>
                      <td><?php echo $result->garage_in_kms; ?></td>
                    </tr>
                    <tr>
                      <th>Work Description </th>
                      <td><?php echo $result->work_description; ?></td>
                    </tr>
                    <tr>
                      <th>Bill Number </th>
                      <td><?php echo $result->bill_no; ?></td>
                    </tr>
                    <tr>
                      <th>Bill Amount </th>
                      <td><?php echo $result->bill_amount; ?></td>
                    </tr>
                    
                    <tr>
                      <th>Payment Status</th>
                      <td><?php echo ucwords($result->payment_status); ?></td>
                    </tr>
                    <tr>
                      <th>Payment Mode</th>
                      <td><?php echo $result->payment_type; ?></td>
                    </tr>
                    <tr>
                      <th>Payment Date </th>
                      <td><?php echo $result->payment_date; ?></td>
                    </tr>
                    <tr>
                      <th>Remarks</th>
                      <td><?php echo $result->remarks; ?></td>
                    </tr>
                    <tr>
                      <th>Next Service Km</th>
                      <td><?php echo $result->next_service_kms; ?></td>
                    </tr>
                    <tr>
                      <th>Insurance Claim Amount</th>
                      <td><?php echo $result->insurance_claim_amount; ?></td>
                    </tr>
                    <tr>
                      <th>Insurance Paid Amount</th>
                      <td><?php echo $result->insurance_amount_paid; ?></td>
                    </tr>
                    <tr>
                      <th>Insurance Paid Date</th>
                      <td><?php echo $result->insurance_paid_date; ?></td>
                    </tr>
                    <tr>
                      <th>Bill Attachment</th>
                      <td>
                          <?php
                          if(isset($result->file_name) && trim($result->file_name)!="" && file_exists($pathname. DIRECTORY_SEPARATOR.$result->file_name)){
                          ?>
                          <a target='_blank' href="<?php echo $this->basePath(). DIRECTORY_SEPARATOR."uploads". DIRECTORY_SEPARATOR."vehicle-service". DIRECTORY_SEPARATOR .$result->service_id. DIRECTORY_SEPARATOR.$result->file_name ?>" ><?php echo $result->file_name; ?></a>
                          <?php
                          }
                          ?>
                      </td>
                    </tr>
                  </table>
                    <br/>
                    <div class="box-footer">
                        <a href="<?php echo $this->url('vehicle-service', array('action' => 'index')); ?>" class="btn btn-default">Back</a>
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->
    </div>

<script type="text/javascript">
    
</script>