<?php
return array(
    'BC002' => array(
        'Admin\\Controller\\Index' => array(
            'index' => 'allow',
            'financial' => 'deny',
            'operation' => 'allow',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'allow',
        ),
        'Admin\\Controller\\VehicleService' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Config' => array(
            'index' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Booking' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-vendor-payment' => 'allow',
            'execute' => 'allow',
            'cancel' => 'allow',
            'close-trip' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'edit-execute' => 'allow',
            'edit-vendor-payment' => 'allow',
            'executed-list' => 'allow',
            'generate-bill' => 'allow',
            'generate-trip-sheet' => 'allow',
            'cancel-list' => 'allow',
            'closed-list' => 'allow',
            'pending' => 'allow',
            'vendor-pending' => 'allow',
        ),
        'Admin\\Controller\\City' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Clients' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Company' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Corporate' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Cyff' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Employee' => array(
            'index' => 'allow',
            'add' => 'allow',
            'change-password' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Marriott' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\MonthlyBilling' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'generate-billing' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Rentals' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Retail' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Roles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Sms' => array(
            'index' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Taj' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\User' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\VehicleType' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\VehicleUsage' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Vehicles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Vendor' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-advance' => 'allow',
            'add-payment' => 'allow',
            'add-rental' => 'allow',
            'all-payment' => 'allow',
            'completed-payment' => 'allow',
            'delete-payment' => 'allow',
            'download-pdf-report' => 'allow',
            'edit' => 'allow',
            'edit-payment' => 'allow',
            'edit-rental' => 'allow',
            'make-payment' => 'allow',
            'ledger' => 'allow',
            'pending-payment' => 'allow',
            'view-ledger' => 'allow',
            'view-payment' => 'allow',
        ),
    ),
    'BC003' => array(
        'Admin\\Controller\\Index' => array(
            'index' => 'deny',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'allow',
        ),
        'Admin\\Controller\\VehicleService' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Config' => array(
            'index' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Booking' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Clients' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Company' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Corporate' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Cyff' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Employee' => array(
            'index' => 'deny',
            'add' => 'deny',
            'change-password' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Marriott' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\MonthlyBilling' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'deny',
            'edit' => 'allow',
            'generate-billing' => 'allow',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Rentals' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Retail' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Roles' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Taj' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\User' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\VehicleType' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\VehicleUsage' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Vehicles' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
            'view' => 'deny',
        ),
    ),
    'BC001' => array(
        'Admin\\Controller\\Index' => array(
            'index' => 'allow',
            'financial' => 'allow',
            'operation' => 'allow',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'allow',
        ),
        'Admin\\Controller\\VehicleService' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'deny',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Fuel' => array(
            'add' => 'allow',
            'edit' => 'allow',
            'reports' => 'allow',
        ),
        'Admin\\Controller\\Config' => array(
            'index' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Booking' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-vendor-payment' => 'allow',
            'execute' => 'allow',
            'cancel' => 'allow',
            'close-trip' => 'allow',
            'closed-list' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'edit-execute' => 'allow',
            'edit-vendor-payment' => 'allow',
            'executed-list' => 'allow',
            'generate-bill' => 'allow',
            'generate-trip-sheet' => 'allow',
            'cancel-list' => 'allow',
            'pending' => 'allow',
            'vendor-pending' => 'allow',
        ),
        'Admin\\Controller\\City' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Clients' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Company' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Corporate' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Cyff' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\CymHotelBooking' => array(
            'add' => 'allow',
            'edit' => 'allow',
            'edit-rentals' => 'allow',
            'rentals' => 'allow',
            'index' => 'allow',
        ),
        'Admin\\Controller\\Employee' => array(
            'index' => 'allow',
            'add' => 'allow',
            'change-password' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\FpsHotelBooking' => array(
            'index' => 'allow',
            'add' => 'allow',
            'complete' => 'allow',
            'edit' => 'allow',
            'reports' => 'allow',
        ),
        'Admin\\Controller\\Hotel' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\HotelBooking' => array(
            'index' => 'allow',
            'add' => 'allow',
            'cancel' => 'allow',
            'complete' => 'allow',
            'edit' => 'allow',
            'generate-trip-sheet' => 'allow',
            'reports' => 'allow',
        ),
        'Admin\\Controller\\Marriott' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\MonthlyBilling' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'generate-billing' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Rentals' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Retail' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Roles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\Sms' => array(
            'index' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Taj' => array(
            'daily-sales' => 'allow',
            'index' => 'allow',
            'add-daily-sales' => 'allow',
            'add' => 'allow',
            'edit-daily-sales' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\User' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\VehicleType' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Admin\\Controller\\VehicleUsage' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Vehicles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'view' => 'allow',
        ),
        'Admin\\Controller\\Vendor' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-advance' => 'deny',
            'add-payment' => 'allow',
            'add-rental' => 'allow',
            'all-payment' => 'deny',
            'completed-payment' => 'allow',
            'delete-payment' => 'allow',
            'download-pdf-report' => 'allow',
            'edit' => 'allow',
            'edit-payment' => 'allow',
            'edit-rental' => 'allow',
            'make-payment' => 'allow',
            'ledger' => 'allow',
            'pending-payment' => 'allow',
            'view-ledger' => 'allow',
            'view-payment' => 'allow',
        ),
    ),
    'BC088' => array(
        'Admin\\Controller\\Index' => array(
            'index' => 'deny',
            'financial' => 'deny',
            'operation' => 'deny',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'deny',
        ),
        'Admin\\Controller\\VehicleService' => array(
            'index' => 'deny',
            'add' => 'deny',
            'delete' => 'deny',
            'edit' => 'deny',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Config' => array(
            'index' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Booking' => array(
            'index' => 'deny',
            'add' => 'deny',
            'add-vendor-payment' => 'deny',
            'execute' => 'deny',
            'cancel' => 'deny',
            'close-trip' => 'deny',
            'closed-list' => 'deny',
            'delete' => 'deny',
            'edit' => 'deny',
            'edit-execute' => 'deny',
            'edit-vendor-payment' => 'deny',
            'executed-list' => 'deny',
            'generate-bill' => 'deny',
            'generate-trip-sheet' => 'deny',
            'cancel-list' => 'deny',
            'pending' => 'deny',
            'vendor-pending' => 'deny',
        ),
        'Admin\\Controller\\City' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Clients' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Company' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Corporate' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Cyff' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Employee' => array(
            'index' => 'deny',
            'add' => 'deny',
            'change-password' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Hotel' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\HotelBooking' => array(
            'index' => 'allow',
            'add' => 'allow',
            'cancel' => 'allow',
            'complete' => 'allow',
            'edit' => 'allow',
            'generate-trip-sheet' => 'deny',
            'reports' => 'allow',
        ),
        'Admin\\Controller\\Marriott' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\MonthlyBilling' => array(
            'index' => 'deny',
            'add' => 'deny',
            'delete' => 'deny',
            'edit' => 'deny',
            'generate-billing' => 'deny',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Rentals' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Retail' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Roles' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Sms' => array(
            'index' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\Taj' => array(
            'daily-sales' => 'deny',
            'index' => 'deny',
            'add-daily-sales' => 'deny',
            'add' => 'deny',
            'edit-daily-sales' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\User' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\VehicleType' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ),
        'Admin\\Controller\\VehicleUsage' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Vehicles' => array(
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
            'view' => 'deny',
        ),
        'Admin\\Controller\\Vendor' => array(
            'index' => 'deny',
            'add' => 'deny',
            'add-advance' => 'deny',
            'add-payment' => 'deny',
            'add-rental' => 'deny',
            'all-payment' => 'deny',
            'completed-payment' => 'deny',
            'delete-payment' => 'deny',
            'download-pdf-report' => 'deny',
            'edit' => 'deny',
            'edit-payment' => 'deny',
            'edit-rental' => 'deny',
            'make-payment' => 'deny',
            'ledger' => 'deny',
            'pending-payment' => 'deny',
            'view-ledger' => 'deny',
            'view-payment' => 'deny',
        ),
    ),
);
