<!DOCTYPE html>
<html>
<?php
use Zend\Session\Container;
$container = new Container('alert');
$loginContainer = new Container('credo');
?>
<head>
    <meta charset="utf-8">
	<title>Beecabs</title>
    <link href="<?php echo $this->basePath() . '/assets/css/bootstrap.min.css'?>" rel="stylesheet">
</head>
<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="<?php echo $this->basePath() . '/assets/js/bootstrap.min.js'?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath().'/assets/js/deforayValidation.js'; ?>"></script>

<body>
    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-5 col-md-offset-3 col-sm-6 col-sm-offset-2">                    
            <div class="panel panel-info" >
				<div class="panel-heading">
					<div class="panel-title">Forgot Password</div>
				</div>
                <div style="padding-top:30px" class="panel-body">
					<form class="form-horizontal" name="forgotInformation" id="forgotInformation"  method="post" action="<?php echo $this->url('login',array('action'=>'forgot-password')); ?>" autocomplete="off">
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label for="roleName" class="col-lg-3 control-label">Email Id </label>
									<div class="col-lg-7">
										<input type="text" class="form-control isEmail isRequired" name="emailId" id="emailId" placeholder="Enter register email id" autofocus title="Please enter your valid email id" />
									</div>
								</div>
							</div>
						</div>
						 <div class="box-footer">
                        <input type="button" class="btn btn-primary" value="Submit" onclick="checkEmailValidation();return false;">
                        <a href="<?php echo $this->url('login', array('action' => 'index')); ?>" class="btn btn-default">Back</a>
                    </div>
					</form>
                </div>                     
            </div>
        </div>
       
    </div>
    
    
<script type="text/javascript">
       $(document).ready(function() {
		<?php
		if (isset($container->alertMsg) && $container->alertMsg != "") {
		    ?>
			alert("<?php echo $container->alertMsg; ?>");
		    <?php
		    $container->alertMsg = "";
		    unset($container->alertMsg);
		}
		?>
        });
       
	function checkEmailValidation(){
		flag = deforayValidator.init({
		    formId: 'forgotInformation'
		});
		if(flag){
			email=$("#emailId").val();
			$.post("<?php echo $this->url('login', array('action' => 'check-login-email')); ?>", {email: email},
			function(data) {
				if (data==0)
				{
					alert("Please enter register email id");
					$("#emailId").val('');
				}
				else {
					document.getElementById('forgotInformation').submit();
				}
			});
		}
	}
	
</script>
</body>
</html>