<!DOCTYPE html>
<html>
<?php
use Zend\Session\Container;
$container = new Container('alert');
$loginContainer = new Container('credo');
?>
<head>
    <meta charset="utf-8">
	<title>Beecabs</title>
    <link href="<?php echo $this->basePath() . '/assets/css/bootstrap.min.css'?>" rel="stylesheet">
	<style>
    body {
  background: #e9e9e9;
  color: #666666;
  font-family: 'RobotoDraft', 'Roboto', sans-serif;
  font-size: 14px;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* Form Module */
.form-module {
  position: relative;
  background: #ffffff;
  max-width: 340px;
  width: 100%;
  border-top: 5px solid #33b5e5;
  box-shadow: 0 0 3px rgba(0, 0, 0, 0.1);
  margin: 0 auto;
}

.form-module .toggle .tooltip {
  position: absolute;
  top: 5px;
  right: -65px;
  display: block;
  background: rgba(0, 0, 0, 0.6);
  width: auto;
  padding: 5px;
  font-size: 10px;
  line-height: 1;
  text-transform: uppercase;
}
.form-module .toggle .tooltip:before {
  content: '';
  position: absolute;
  top: 15px;
  left: -5px;
  display: block;
  border-top: 5px solid transparent;
  border-bottom: 5px solid transparent;
  border-right: 5px solid rgba(0, 0, 0, 0.6);
}
.form-module .form {
  display: none;
  padding: 40px;
}
.form-module .form:nth-child(2) {
  display: block;
}
.form-module h2 {
  margin: 0 0 20px;
  color: #33b5e5;
  font-size: 18px;
  font-weight: 400;
  line-height: 1;
}

.form-module input:focus {
  border: 1px solid #33b5e5;
  color: #333333;
}
.form-module button {
  cursor: pointer;
  background: #33b5e5;
  width: 100%;
  border: 0;
  padding: 10px 15px;
  color: #ffffff;
  -webkit-transition: 0.3s ease;
  transition: 0.3s ease;
}
.form-module button:hover {
  background: #178ab4;
}

</style>
</head>
<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="<?php echo $this->basePath() . '/assets/js/bootstrap.min.js'?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath().'/assets/js/deforayValidation.js'; ?>"></script>
<body>
    <br/><br/>
<!-- Form Module-->
<div class="module form-module">
  <div >
  </div>
  <div class="form">
    <div style="text-align: center;margin-top: -8%;">
    <img src="<?php echo $this->basePath().'/assets/img/logo.png';?>"/>
    </div>
    <!--<h2 align="center">Please sign in to proceed</h2>-->
    <br/>
    <form class="" method="post" name="adminLoginInformation" id="adminLoginInformation" action="<?php echo $this->url('login',array('action'=>'index')); ?>" autocomplete="off" onsubmit="return doLogin();return false;">
	    <div class="form-group">
		<div class="input-group ">
		<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		<input type="text" class="form-control isRequired" name="userId" id="userId" value="" placeholder="Enter user name" autofocus title="Please enter your user name" />
		</div>
	    </div>
	    <div class="form-group">
		<div class="input-group">
		<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
		<input type="password" class="form-control isRequired" name="password" placeholder="Enter password" title="Please enter your password">
		</div>
	    </div>
		
		<div class="row">
		  <div class="col-md-6">
			<div class="form-group">
			  <div class="checkbox">
			  <label>
				<input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
			  </label>
			</div>
			</div>
		  </div>
		  
		  <div class="col-md-6">
			<div class="form-group">
			  <div class="checkbox">
			  <a href="<?php echo $this->url('login', array('action' => 'forgot-password'));  ?>"  title="Forgot Password">Forgot Password?</a>
			</div>
			</div>
		  </div>
		</div>
	    <button onClick="doLogin();return false;" title="Login">Login</button><br/><br/>
    </form>
    
  </div>
</div>


<script type="text/javascript">
       $(document).ready(function() {
		<?php
		if (isset($container->alertMsg) && $container->alertMsg != "") {
		    ?>
			alert("<?php echo $container->alertMsg; ?>");
		    <?php
		    $container->alertMsg = "";
		    unset($container->alertMsg);
		}
		?>
        });
       
	function doLogin(){
		flag = deforayValidator.init({
		    formId: 'adminLoginInformation'
		});
		
		if(flag){
		    document.getElementById('adminLoginInformation').submit();
		}
	}
	
</script>
</body>
</html>
