<?php
use Zend\Session\Container;
$container = new Container('alert');
$sessionLogin = new Container('credo');
echo $this->doctype();
$role = $sessionLogin->employeeCode;
$adminMenu = "";
$dailySalesMenu = "";
$fleetMenu = "";
$vendorPaymentMenu = "";
$bookingMenu = "";
$cyffHotelMenu = "";
$fpsHotelMenu = "";
$fuelMenu = "";
$cymHotelMenu="";

if(isset($sessionLogin->roleId) && trim($sessionLogin->roleId)=="1"){
	$dashboardLink=$this->url('admin-home', array('action' => 'index'));
}else{
	$dashboardLink=$this->url('home', array('action' => 'index'));
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Company", "index")) {
	$adminMenu.="<li><a href=" . $this->url('company', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Company</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Roles", "index")) {
	$adminMenu.="<li><a href=" . $this->url('roles', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Roles</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Config", "index")) {
	$adminMenu.="<li><a href=" . $this->url('config', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> General Config</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\City", "index")) {
	$adminMenu.="<li><a href=" . $this->url('city', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> City</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\VehicleType", "index")) {
	$adminMenu.="<li><a href=" . $this->url('vehicle-type', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Vehicle Type</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vehicles", "index")) {
	$adminMenu.="<li><a href=" . $this->url('vehicles', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Vehicles</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Clients", "index")) {
	$adminMenu.="<li><a href=" . $this->url('clients', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Clients</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Employee", "index")) {
	$adminMenu.="<li><a href=" . $this->url('employee', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Employee</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\User", "index")) {
	$adminMenu.="<li><a href=" . $this->url('user', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Users</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Rentals", "index")) {
	$adminMenu.="<li><a href=" . $this->url('rentals', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Rentals</a></li>";
}
/*
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Corporate", "index")) {
	$adminMenu.="<li><a href=" . $this->url('corporate', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Corporate Target</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Marriott", "index")) {
	$adminMenu.="<li><a href=" . $this->url('marriott', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Marriott Target</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Retail", "index")) {
	$adminMenu.="<li><a href=" . $this->url('retail', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Retail Target</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Taj", "index")) {
	$adminMenu.="<li><a href=" . $this->url('taj', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Taj Target</a></li>";
}
*/
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "index")) {
	$adminMenu.="<li><a href=" . $this->url('vendor', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Vendors</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Hotel", "index")) {
	$adminMenu.="<li><a href=" . $this->url('hotel', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Hotel </a></li>";
}
//if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Sms", "index")) {
//	$adminMenu.="<li><a href=" . $this->url('sms', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> SMS Template</a></li>";
//}

//Daily Sales Menu
/*
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Corporate", "daily-sales")) {
	$dailySalesMenu.="<li><a href=" . $this->url('corporate', array('action' => 'daily-sales')) . "><i class='fa fa-angle-double-right'></i> Corporate</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Cyff", "index")) {
	$dailySalesMenu.="<li><a href=" . $this->url('cyff', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Cyff</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Marriott", "daily-sales")) {
	$dailySalesMenu.="<li><a href=" . $this->url('marriott', array('action' => 'daily-sales')) . "><i class='fa fa-angle-double-right'></i> Marriott</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Retail", "daily-sales")) {
	$dailySalesMenu.="<li><a href=" . $this->url('retail', array('action' => 'daily-sales')) . "><i class='fa fa-angle-double-right'></i> Retail</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Taj", "daily-sales")) {
	$dailySalesMenu.="<li><a href=" . $this->url('taj', array('action' => 'daily-sales')) . "><i class='fa fa-angle-double-right'></i> Taj</a></li>";
}
*/
//Fleet Menu
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\VehicleService", "index")) {
	$fleetMenu.="<li><a href=" . $this->url('vehicle-service', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Vehicle Service</a></li>";
}

//Vendor Payment
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "all-payment")) {
	//$vendorPaymentMenu.="<li><a href=" . $this->url('vendor', array('action' => 'all-payment')) . "><i class='fa fa-angle-double-right'></i>Vendor Payment List</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "pending-payment")) {
	//$vendorPaymentMenu.="<li><a href=" . $this->url('vendor', array('action' => 'pending-payment')) . "><i class='fa fa-angle-double-right'></i> Pending Payment</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "completed-payment")) {
	//$vendorPaymentMenu.="<li><a href=" . $this->url('vendor', array('action' => 'completed-payment')) . "><i class='fa fa-angle-double-right'></i> Completed Payment</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "add-advance")) {
	$vendorPaymentMenu.="<li><a href=" . $this->url('vendor', array('action' => 'add-advance')) . "><i class='fa fa-circle-o text-aqua'></i> Add Vendor Advance </a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "add-payment")) {
	$vendorPaymentMenu.="<li><a href=" . $this->url('vendor', array('action' => 'add-payment')) . "><i class='fa fa-circle-o text-aqua'></i> Add Vendor Payment </a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Vendor", "ledger")) {
	$vendorPaymentMenu.="<li><a href=" . $this->url('vendor', array('action' => 'ledger')) . "><i class='fa fa-circle-o text-aqua'></i> Vendor Ledger </a></li>";
}
//Booking Menu
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "add")) {
	$bookingMenu.="<li><a href=" . $this->url('booking', array('action' => 'add')) . "><i class='fa fa-angle-double-right'></i> New Booking</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "pending")) {
	$bookingMenu.="<li><a href=" . $this->url('booking', array('action' => 'pending')) . "><i class='fa fa-angle-double-right'></i> Pending Booking</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "executed-list")) {
	$bookingMenu.="<li><a href=" . $this->url('booking', array('action' => 'executed-list')) . "><i class='fa fa-angle-double-right'></i> Executed Booking</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "closed-list")) {
	$bookingMenu.="<li><a href=" . $this->url('booking', array('action' => 'closed-list')) . "><i class='fa fa-angle-double-right'></i> Closed Booking</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "vendor-pending")) {
	$bookingMenu.="<li><a href=" . $this->url('booking', array('action' => 'vendor-pending')) . "><i class='fa fa-angle-double-right'></i> Vendor Pending</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "cancel-list")) {
	$bookingMenu.="<li><a href=" . $this->url('booking', array('action' => 'cancel-list')) . "><i class='fa fa-angle-double-right'></i> Cancel Booking</a></li>";
}


if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\HotelBooking", "add")) {
	$cyffHotelMenu.="<li><a href=" . $this->url('hotel-booking', array('action' => 'add')) . "><i class='fa fa-angle-double-right'></i> New Booking</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\HotelBooking", "reports")) {
	$cyffHotelMenu.="<li><a href=" . $this->url('hotel-booking', array('action' => 'reports')) . "><i class='fa fa-angle-double-right'></i> Reports</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\FpsHotelBooking", "add")) {
	$fpsHotelMenu.="<li><a href=" . $this->url('fps-hotel-booking', array('action' => 'add')) . "><i class='fa fa-angle-double-right'></i> New Booking</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\FpsHotelBooking", "reports")) {
	$fpsHotelMenu.="<li><a href=" . $this->url('fps-hotel-booking', array('action' => 'reports')) . "><i class='fa fa-angle-double-right'></i> Reports</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Fuel", "add")) {
	$fuelMenu.="<li><a href=" . $this->url('fuel', array('action' => 'add')) . "><i class='fa fa-angle-double-right'></i> Add Fuel</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Fuel", "reports")) {
	$fuelMenu.="<li><a href=" . $this->url('fuel', array('action' => 'reports')) . "><i class='fa fa-angle-double-right'></i> Reports</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\CymHotelBooking", "rentals")) {
	$cymHotelMenu.="<li><a href=" . $this->url('cym-hotel-booking', array('action' => 'rentals')) . "><i class='fa fa-angle-double-right'></i> Rental List</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\CymHotelBooking", "add")) {
	$cymHotelMenu.="<li><a href=" . $this->url('cym-hotel-booking', array('action' => 'add')) . "><i class='fa fa-angle-double-right'></i> New Booking</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\CymHotelBooking", "index")) {
	$cymHotelMenu.="<li><a href=" . $this->url('cym-hotel-booking', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i> Reports</a></li>";
}
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Beecabs</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <!-- Bootstrap 3.3.6 -->
  <link href="<?php echo $this->basePath() . '/assets/css/bootstrap.min.css'?>" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/28e7751dbec/integration/bootstrap/3/dataTables.bootstrap.css">
  
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/skins/_all-skins.min.css' ?>">
  <!--files-->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/timepicker/bootstrap-timepicker.min.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/select2.min.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/daterangepicker/daterangepicker.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/datepicker3.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/jasny-bootstrap.min.css' ?>">
	<!-- Theme style -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/AdminLTE.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/deforayModal.css';?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/style.css' ?>">
  
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  
	<style>
  .main-header #headerLogo:before{
	content:none !important;
  }
  .letterImg{
	float: left;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    margin-right: 10px;
    margin-top: -11px;
	background:#215682;
	text-align:center;
  }
  .navbar{
	-webkit-box-shadow: 0 5px 5px -6px #777;
       -moz-box-shadow: 0 5px 5px -6px #777;
            box-shadow: 0 5px 5px -6px #777;
  }
  
  .skin-black .main-sidebar{
	    background-color: #224d70;
  }
  .skin-black .sidebar-menu>li>.treeview-menu{
	background:#175e93;
  }
  .skin-black .sidebar-menu>li:hover>a, .skin-black .sidebar-menu>li.active>a{
	background-color: #224d70;
  }
</style>
	<!-- jQuery 2.2.3 -->
<script src="<?php echo $this->basePath() . '/assets/plugins/jQuery/jquery-2.2.3.min.js' ?>"></script>
</head>
<body class="hold-transition skin-black sidebar-mini sidebar-collapse ">
<div class="wrapper">

  <header class="main-header">
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
		<div href="#" class="sidebar-toggle" id="headerLogo" style="padding:0 !important;font-family:arial !important;border-right:none;">
			<img src="<?php echo $this->basePath() . '/assets/img/logo.png'; ?>" class="user-image" alt="Logo Image" style="height:38px;margin-top:5px;margin-left:4px;">
		</div>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
			<?php
		  if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Index", "financial")) {
		  ?>
          <li class="dropdown">
            <a href="<?php echo $this->url('admin-home',array('action'=>'financial')); ?>"> Finance Dashboard  </a>
          </li>
		  <?php } ?>
		  <?php
		  if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Index", "operation")) {
		  ?>
		  <li class="dropdown">
            <a href="<?php echo $this->url('admin-home',array('action'=>'operation')); ?>"> Operation Dashboard  </a>
          </li>
		  <?php } ?>
		  <?php
		  if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\Booking", "pending")) {
		  ?>
		  <li class="dropdown">
            <a href="<?php echo $this->url('booking', array('action' => 'pending')); ?>" > Manage Booking  </a>
          </li>
		  <?php } ?>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <div class="letterImg"><p style="color:#fff;font-weight:bold !important;margin-top:9px;font-size:20px;"><?php echo $sessionLogin->empLetters; ?></p></div>
			  <?php echo $sessionLogin->name." - ".$sessionLogin->employeeCode;?>
              <span class="hidden-xs"></span>
            </a>
            <ul class="dropdown-menu">
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<?php echo $this->url('employee',array('action'=>'change-password')); ?>" class="btn btn-default btn-flat">Change Password</a>
                </div>
                <div class="pull-right">
                  <a href="<?php echo $this->url('login',array('action'=>'logout')); ?>" class="btn btn-default btn-flat">Log out</a>
                </div>
              </li>
            </ul>
          </li>
          
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
     
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <?php if($dashboardLink!=""){
			if (isset($acl) && ($acl->isAllowed($role, "Admin\Controller\Index", "index") || $acl->isAllowed($role, "Application\Controller\Index", "index")) ) {
		?>
		<li>
          <a href="<?php echo $dashboardLink; ?>">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
		</li>
		<?php } } ?>
				<?php if($adminMenu!=""){ ?>
				<li class="treeview">
          <a href="#">
            <i class="fa fa-cogs"></i> <span>Manage</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu" style="display: none;">
            <?php if($adminMenu!=''){ echo $adminMenu; } ?>
          </ul>
				</li>
				<?php } ?>
				<?php if($fleetMenu!=""){ ?>
				<li class="treeview">
          <a href="#">
            <i class="fa fa-car"></i>
            <span>Fleet Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
						<?php if($fleetMenu!=''){ echo $fleetMenu; } ?>
          </ul>
        </li>
				<?php } ?>
		<?php
		/*
		if(trim($dailySalesMenu)!=""){
		?>
				<li class="treeview">
          <a href="#">
            <i class="fa fa-calendar"></i>
            <span>Daily Sales</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
				<?php if($dailySalesMenu!=''){ echo $dailySalesMenu; } ?>
          </ul>
        </li>
		<?php } */ ?>
		
		<?php if($bookingMenu!=""){ ?>
		<li class="treeview">
          <a href="#">
            <i class="fa fa-book"></i>
            <span>Booking</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
			<?php if($bookingMenu!=''){ echo $bookingMenu; } ?>
          </ul>
        </li>
		<?php } ?>
		
		<?php
		if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\VehicleUsage", "index")) {
		?>
		<li>
          <a href="<?php echo $this->url('vehicle-usage', array('action' => 'index'));?>">
            <i class="fa fa-briefcase"></i> <span>Vehicle Usage</span>
          </a>
        </li>
		<?php } ?>
		<?php
		if (isset($acl) && $acl->isAllowed($role, "Admin\Controller\MonthlyBilling", "index")) {
		?>
		<li>
          <a href="<?php echo $this->url('monthly-billing', array('action' => 'index'));?>">
            <i class="fa fa-calendar"></i> <span>Monthly Billing</span>
          </a>
        </li>
		<?php } ?>
		<?php if($vendorPaymentMenu!=""){ ?>
		<li class="treeview">
          <a href="#">
            <i class="fa fa-money"></i>
            <span>Vendor Payment</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
			<?php if($vendorPaymentMenu!=''){ echo $vendorPaymentMenu; } ?>
          </ul>
        </li>
		<?php } ?>
		
		<?php if($cyffHotelMenu!=""){ ?>
		<li class="treeview">
          <a href="#">
            <i class="fa fa-hotel"></i>
            <span>CYFF Hotel Booking</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
			<?php if($cyffHotelMenu!=''){ echo $cyffHotelMenu; } ?>
          </ul>
        </li>
		<?php } ?>
		
		<?php if($fpsHotelMenu!=""){ ?>
		<li class="treeview">
          <a href="#">
            <i class="fa fa-hotel"></i>
            <span>FPS Hotel Booking</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
			<?php if($fpsHotelMenu!=''){ echo $fpsHotelMenu; } ?>
          </ul>
        </li>
		<?php } ?>
		
    <?php if($cymHotelMenu!=""){ ?>
		<li class="treeview">
          <a href="#">
            <i class="fa fa-hotel"></i>
            <span>CYM Hotel Booking</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
			<?php if($cymHotelMenu!=''){ echo $cymHotelMenu; } ?>
          </ul>
        </li>
		<?php } ?>

		<?php if($fuelMenu!=""){ ?>
		<li class="treeview">
          <a href="#">
            <i class="fa fa-automobile"></i>
            <span>Fuel Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
			<?php if($fuelMenu!=''){ echo $fuelMenu; } ?>
          </ul>
        </li>
		<?php } ?>
		
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="background:#fff;">
    <?php echo $this->content; ?>
    <?php echo (isset($this->aclError) ? $this->aclError : ""); ?>
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
   
    <strong>Copyright &copy; 2016-2017 <a href="#">Beecabs</a>.</strong> All rights
    reserved.
  </footer>

  
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
<!-- ./wrapper -->
<div id="dDiv" class="dialog"> 
    <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
    <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
</div>

<!-- Bootstrap 3.3.6 -->
<script src="<?php echo $this->basePath() . '/assets/js/bootstrap.min.js'?>"></script>
<!-- DataTables -->
<script src="<?php echo $this->basePath() . '/assets/plugins/datatables/jquery.dataTables.min.js' ?>"></script>
<!--
<script src="< ?php echo $this->basePath() . '/assets/plugins/datatables/dataTables.bootstrap.min.js' ?>"></script>
-->
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/28e7751dbec/integration/bootstrap/3/dataTables.bootstrap.js"></script>
<script src="<?php echo $this->basePath() . '/assets/plugins/daterangepicker/daterangepicker.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/plugins/datepicker/bootstrap-datepicker.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/plugins/timepicker/bootstrap-timepicker.min.js' ?>"></script>
<!-- Slimscroll -->
<script src="<?php echo $this->basePath() . '/assets/plugins/slimScroll/jquery.slimscroll.min.js' ?>"></script>
<!-- FastClick -->
<script src="<?php echo $this->basePath() . '/assets/plugins/fastclick/fastclick.js' ?>"></script>
<!-- AdminLTE App -->
<script src="<?php echo $this->basePath() . '/assets/js/app.min.js' ?>"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo $this->basePath() . '/assets/js/deforayValidation.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/jquery.blockUI.js'; ?>"></script>

<script src="<?php echo $this->basePath() . '/assets/js/select2.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/deforayModal.js'; ?>"></script>
<!-- page script -->
<script>
  $(function () {
    <?php
            if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
                alert("<?php echo $container->alertMsg; ?>");
                <?php
                $container->alertMsg = "";
                unset($container->alertMsg);
            }
    ?>
    
  });
  jQuery(".checkNum").keydown(function (e) {
	      // Allow: backspace, delete, tab, escape, enter and .
	      if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
		       // Allow: Ctrl+A
		      (e.keyCode == 65 && e.ctrlKey === true) || 
		       // Allow: home, end, left, right
		      (e.keyCode >= 35 && e.keyCode <= 39)) {
			       // let it happen, don't do anything
			       return;
	      }
	      // Ensure that it is a number and stop the keypress
	      if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
		      e.preventDefault();
	      }
  });
  
  function checkNum(){
	  jQuery(".checkNum").keydown(function (e) {
	      // Allow: backspace, delete, tab, escape, enter and .
	      if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
		       // Allow: Ctrl+A
		      (e.keyCode == 65 && e.ctrlKey === true) || 
		       // Allow: home, end, left, right
		      (e.keyCode >= 35 && e.keyCode <= 39)) {
			       // let it happen, don't do anything
			       return;
	      }
	      // Ensure that it is a number and stop the keypress
	      if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
		      e.preventDefault();
	      }
  });
  }
  
	function showModal(url, w, h) {
		showdefModal('dDiv', w, h);
		document.getElementById('dFrame').style.height = h + 'px';
		document.getElementById('dFrame').style.width = w + 'px';
		document.getElementById('dFrame').src = url;
    }
	function closeModal() {
		document.getElementById('dFrame').src = "";
		hidedefModal('dDiv');
	}
	
	function deleteBooking(bookingId){
		conf=confirm("Are you sure, you want to delete this booking");
		if(conf){
			$.post("<?php echo $this->url('booking', array('action' => 'delete')); ?>", {bookingId:bookingId},
            function(data){
                if (data>0) {
					alert("Deleted successfully");
					oTable.fnDraw();
                }
            });
		}
	}
	
	
	$(".sidebar-menu li" ).click(function() {
		if($("body").hasClass("sidebar-open")) {
			$("body").removeClass("sidebar-collapse");
		}
	});
</script>
</body>
</html>
