<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->employeeCode;
$acl=$this->layout()->acl;
if ($acl->isAllowed($role, 'Admin\Controller\Sms', 'edit')) {
	$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
}else{
	$editAction = '{"sClass":"center"},{"sClass":"center"}';
}
?>
<!-- Content Header (Page header) -->
<div class="content-wrapper">
<section class="content-header">
	
    <div class="pull-left">
		<ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
			<div class="panel panel-primary">
            <div class="panel-heading">
              <h2 class="panel-title" style=""><i class="fa fa-cogs"></i> SMS Template List</h2>
            </div>
			<!-- /.box-header -->
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">
							<div class="box-body">
								<table id="smsDataTable" class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>SMS Name</th>
											<th>Message</th>
											<?php
											if ($acl->isAllowed($role, 'Admin\Controller\Sms', 'edit')) {
											?>
											<th>Action</th>
											<?php } ?>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="4" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
									
								</table>
							</div><!-- /.box-body -->
						</div>
					</div>
				</div>
          </div>
          <!-- /.panel -->
            
        </div>
    </div>
</section><!-- /.content -->
</div>
<script type="text/javascript">
    /* Table initialisation */
     oTable = null;
    $(document).ready(function() {
    $('#smsDataTable').dataTable( {
		"bAutoWidth": false,
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		<?php echo $editAction;?>
            ],
        "sAjaxSource": "<?php echo $this->url('sms',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
    } );

} );
       
</script>
