<!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Add </span>
				<span class="pageHeadingLabe12"> Corporate Daily Sale</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('corporate', array('action' => 'daily-sales')); ?>" class="btn btn-default">Cancel</a>
                    <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                <li><a href="<?php echo $this->url('corporate', array('action' => 'daily-sales')); ?>"> Corporate Daily Sales</a></li>
                <li class="active">Add Corporate Daily Sale</li>
				</ol>
			</div>
		</div>
  </section>

<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addCorporateDailySales" id="addCorporateDailySales"  method="post" action="<?php echo $this->url('corporate', array('action' => 'add-daily-sales')); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Sales Date <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired readonly" id="salesDate" name="salesDate" placeholder="Select sales date" title="Please select sales date" readonly="readonly"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="qualcomm" class="col-lg-4 control-label">Qualcomm </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="qualcomm" name="qualcomm" placeholder="Enter qualcomm" title="Please enter qualcomm" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="kuehneHagel" class="col-lg-4 control-label">Kuehne Hagel </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="kuehneHagel" name="kuehneHagel" placeholder="Enter kuehne hagel" title="Please enter kuehne hagel" onkeyup="calculateTarget()" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="franklinTempleton" class="col-lg-4 control-label">Franklin Templeton</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="franklinTempleton" name="franklinTempleton" placeholder="Enter franklin templeton" title="Please enter franklin templeton" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="cocoCola" class="col-lg-4 control-label">Coco Cola </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="cocoCola" name="cocoCola" placeholder="Enter coco cola" title="Please enter coco cola" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="hospira" class="col-lg-4 control-label">Hospira</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="hospira" name="hospira" placeholder="Enter hospira" title="Please enter hospira" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="kubota" class="col-lg-4 control-label">Kubota </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="kubota" name="kubota" placeholder="Enter kubota" title="Please enter kubota" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="khHyd" class="col-lg-4 control-label">KH HYd</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="khHyd" name="khHyd" placeholder="Enter KH HYD" title="Please enter KH HYD" onkeyup="calculateTarget();"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="sojitz" class="col-lg-4 control-label">Sojitz </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="sojitz" name="sojitz" placeholder="Enter sojitz" title="Please enter sojitz" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="gamesa" class="col-lg-4 control-label">Gamesa</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="gamesa" name="gamesa" placeholder="Enter gamesa" title="Please enter gamesa" onkeyup="calculateTarget()"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="online" class="col-lg-4 control-label">Online </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="online" name="online" placeholder="Enter online" title="Please enter online" onkeyup="calculateTarget()" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="others" class="col-lg-4 control-label">Others </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum calTarget" id="others" name="others" placeholder="Enter others" title="Please enter others" onkeyup="calculateTarget()" />
                                </div>
                            </div>
                        </div>
                        
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="driverDeployed" class="col-lg-4 control-label">Daily Target</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired checkNum readonly" id="dailyTarget" name="dailyTarget" placeholder="Enter daily target" title="Please enter daily target" readonly="readonly" value="<?php echo "-".$targetResult['dailyTarget']; ?>"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="monthlyTarget" class="col-lg-4 control-label">Monthly Target </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum readonly" id="monthlyTarget" name="monthlyTarget" placeholder="Enter monthly target" title="Please enter target" readonly="readonly" value="0"/>
                                    <input type="hidden" class="form-control" id="currentTarget" name="currentTarget" readonly="readonly" value="<?php echo $targetResult['currentTarget']; ?>"/>
                                    <input type="hidden" class="form-control" id="corporateId" name="corporateId" value="<?php echo base64_encode($targetResult['corporateId']); ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <input type="hidden" class="form-control checkNum"  name="globalDailyTarget" id="globalDailyTarget" value="<?php echo $targetResult['dailyTarget']; ?>"/>
                    <input type="hidden" class="form-control checkNum" name="globalMonthlyTarget" id="globalMonthlyTarget" value="<?php echo $targetResult['monthlyTarget']; ?>"/>
                    
                    <div class="box-footer">
                        <a href="<?php echo $this->url('corporate', array('action' => 'daily-sales')); ?>" class="btn btn-default">Cancel</a>
                        <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    selectedDate="";
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'addCorporateDailySales'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('addCorporateDailySales').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        $.blockUI();
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: selectedDate, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                $.unblockUI();
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
                $.unblockUI();
            }
        });
    }
    $(function() {
		$('#salesDate').datepicker({
            //todayBtn: "linked",
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
			format: 'dd-M-yyyy',
            startDate:'<?php echo $targetResult['startTargetDate']; ?>',
            endDate:'<?php echo $targetResult['endTargetDate']; ?>'
		}).on('changeDate', function(e) {
          // `e` here contains the extra attributes
          var date = new Date($('#salesDate').val());
          var day = date.getDate();
          var monthIndex = date.getMonth()+parseInt(1);
          var year = date.getFullYear();
          selectedDate=year+"-"+monthIndex+"-"+day;
          //console.log($('#salesDate').val());
          checkNameValidation('corporate_daily_sales','sales_date',this,null, 'Already exist this sale date . Please select another date.');
        });
	});
    
    function calculateTarget() {
        totalTarget=0;
        currentTarget=$("#currentTarget").val();
        if (currentTarget=='') {
            currentTarget=0;
        }
        $(".calTarget").each(function() {
          if(this.value>0){
            totalTarget=parseFloat(this.value)+parseFloat(totalTarget);
          }
        });
       // $("#totalSales").val(totalTarget);
        todayTarget=parseFloat($("#globalDailyTarget").val())-parseFloat(totalTarget);
        if(parseFloat(todayTarget)>0){
            todayTarget=todayTarget*-1;
        }else{
            todayTarget=todayTarget*-1;
            //todayTarget=Math.abs(todayTarget);
        }
        monthlyTarget=parseFloat(currentTarget)+parseFloat(todayTarget);
        //if(parseFloat(monthlyTarget)>0){
        //    monthlyTarget=monthlyTarget*-1;
        //}else{
        //    monthlyTarget=monthlyTarget*-1;
        //}
        $("#dailyTarget").val(todayTarget);
        $("#monthlyTarget").val(monthlyTarget);
    }
</script>
