  <!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Add </span>
				<span class="pageHeadingLabe12"> Corporate Target</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('corporate', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                        <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                <li><a href="<?php echo $this->url('corporate', array('action' => 'index')); ?>"> Corporate</a></li>
                <li class="active">Add Corporate Target</li>
				</ol>
			</div>
		</div>
  </section>

<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addCorporateTargetInfo" id="addCorporateTargetInfo"  method="post" action="<?php echo $this->url('corporate', array('action' => 'add')); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Target Month <span class="mandatory">*</span></label>
                                <div class="col-lg-6 input-append date" id="dpMonths" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                                    <input type="text" class="form-control isRequired readonly" id="targetMonth" name="targetMonth" placeholder="Select target month & year" title="Please select target month and year" readonly="readonly"/>
                                    <span class="add-on"><i class="icon-calendar"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="dailyTarget" class="col-lg-4 control-label">Daily Target <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired checkNum " id="dailyTarget" name="dailyTarget" placeholder="Enter daily target" title="Please enter daily target" onkeyup="calMonthlyTarget()"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                     <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="monthlyTarget" class="col-lg-4 control-label">Monthly Target <span class="mandatory">*</span> </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired checkNum " id="monthlyTarget" name="monthlyTarget" placeholder="Enter monthly target" title="Please enter monthly target"/>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="box-footer">
                        <a href="<?php echo $this->url('corporate', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                        <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->
    

<script type="text/javascript">
    duplicateName = true;
    selectedDate="";
    noOfDays="";
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'addCorporateTargetInfo'
        });
        if (flag) {
            if (duplicateName) {
              document.getElementById('addCorporateTargetInfo').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        $.blockUI();
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: selectedDate, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById('targetMonth').value = "";
                $.unblockUI();
            }
            else {
                duplicateName = true;
                $.unblockUI();
            }
        });
    }
    
    $(function() {
        $('#dpMonths').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
			format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
		}).on('changeDate', function(e) {
          // `e` here contains the extra attributes
          var date = new Date($('#targetMonth').val());
          var day = date.getDate();
          var monthIndex = date.getMonth()+parseInt(1);
          var year = date.getFullYear();
          selectedDate=year+"-"+monthIndex+"-01";
          checkNameValidation('corporate', 'target_date',this, null, 'Already exist this date and month . Please select another date.');
          getDaysInMonth(monthIndex,year);
        });
		
	});
    
    function getDaysInMonth(selectedMonth,selectedYear){
        noOfDays=new Date(selectedYear,selectedMonth,0).getDate();
        calMonthlyTarget();
    }
    
    function calMonthlyTarget(){
        dailyTarget=$("#dailyTarget").val();
        if(dailyTarget!=""){
            monthlyTarget=dailyTarget*noOfDays;
            $("#monthlyTarget").val(monthlyTarget);
        }
    }
    
</script>
