  <!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Edit </span>
				<span class="pageHeadingLabe12">Taj Target</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('taj', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                    <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                <li><a href="<?php echo $this->url('taj', array('action' => 'index')); ?>"> Taj</a></li>
                <li class="active">Edit Taj Target</li>
				</ol>
			</div>
		</div>
  </section>
 
<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addMarriottDailySales" id="addMarriottDailySales"  method="post" action="<?php echo $this->url('taj', array('action' => 'edit')); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Target Month <span class="mandatory">*</span></label>
                                <div class="col-lg-6 input-append date" id="dpMonths" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                                    <input type="text" class="form-control isRequired readonly" id="targetMonth" name="targetMonth" placeholder="Select target month & year" title="Please select target month and year" readonly="readonly" value="<?php echo $result['target_month']."-".$result['target_year']; ?>"/>
                                    <span class="add-on"><i class="icon-calendar"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="dailyTarget" class="col-lg-4 control-label">Daily Target <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired checkNum " id="dailyTarget" name="dailyTarget" placeholder="Enter daily target" title="Please enter daily target" value="<?php echo $result['daily_target']; ?>" onkeyup="calMonthlyTarget()"/>
                                    <input type="hidden" class="form-control isRequired " id="tajId" name="tajId" value="<?php echo base64_encode($result['taj_id']); ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                     <div class="row">
                        
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="monthlyTarget" class="col-lg-4 control-label">Monthly Target <span class="mandatory">*</span> </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired checkNum " id="monthlyTarget" name="monthlyTarget" placeholder="Enter monthly target" title="Please enter monthly target" value="<?php echo $result['monthly_target']; ?>"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control" id="status" name="status" title="Please select status">
                                        <option value="active" <?php echo(($result['target_status']=='active') ? "selected='selected'" : "") ?>>Active</option>
                                        <option value="inactive" <?php echo(($result['target_status']=='inactive') ? "selected='selected'" : "") ?>>Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="box-footer">
                        <a href="<?php echo $this->url('taj', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                        <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    selectedDate="";
    noOfDays="";
    function validateNow() {

        flag = deforayValidator.init({
            formId: 'addMarriottDailySales'
        });
        if (flag) {
            if (duplicateName) {
              document.getElementById('addMarriottDailySales').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        $.blockUI();
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: selectedDate, fnct: fnct},
        function(data) {
            if (data > 0)
            {
              $.unblockUI();
              alert(msg);
              duplicateName = false;
              document.getElementById('targetMonth').value = "";
            }
            else {
              duplicateName = true;
              $.unblockUI();
            }
        });
    }
    
    $(function() {
        $('#dpMonths').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
			format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
		}).on('changeDate', function(e) {
          // `e` here contains the extra attributes
          var date = new Date($('#targetMonth').val());
          var day = date.getDate();
          var monthIndex = date.getMonth()+parseInt(1);
          var year = date.getFullYear();
          selectedDate=year+"-"+monthIndex+"-01";
          checkNameValidation('taj', 'target_date',this,'<?php echo "taj_id##" .$result['taj_id']; ?>', 'Already exist this date and month . Please select another date.');
          getDaysInMonth(monthIndex,year);
        });
		
	});
    function getDaysInMonth(selectedMonth,selectedYear){
        noOfDays=new Date(selectedYear,selectedMonth,0).getDate();
        calMonthlyTarget();
    }
    
    function calMonthlyTarget(){
        dailyTarget=$("#dailyTarget").val();
        if(dailyTarget!=""){
            monthlyTarget=dailyTarget*noOfDays;
            $("#monthlyTarget").val(monthlyTarget);
        }
    }
    
    
</script>