<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->employeeCode;
$acl=$this->layout()->acl;
$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';

if ($acl->isAllowed($role, 'Admin\Controller\FpsHotelBooking', 'edit')) {
	$editAction.= ',{"sClass":"center icon-btn","bSortable":false}';
}
if ($acl->isAllowed($role, 'Admin\Controller\FpsHotelBooking', 'complete')) {
	$editAction.=',{"sClass":"center icon-btn","bSortable":false}';
}

?>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/custom-style.css' ?>">
	
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-xs-11" style="margin-left:4%">
				<div class="panel panel-primary">
					<div class="panel-heading">
					  <h2 class="panel-title" style=""> Manage Hotel Booking</h2>
					</div>
				<!-- /.box-header -->
					<div class="panel-body">
						<div class="row">
							&nbsp;
							<?php
								if ($acl->isAllowed($role, 'Admin\Controller\FpsHotelBooking', 'add')) {
							?>
								<a href="<?php echo $this->url('fps-hotel-booking',array('action' => 'add'));?>" class="btn btn-primary ">New Booking</a>
							<?php } ?>
							<?php
							if ($acl->isAllowed($role, 'Admin\Controller\FpsHotelBooking', 'reports')) {
							?>
								<a href="<?php echo $this->url('fps-hotel-booking',array('action' => 'reports'));?>" class="btn btn-primary ">Reports</a>
							<?php } ?>
							<a href="<?php //echo $this->url('hotel-booking',array('action' => 'reports'));?>" class="btn btn-primary ">Analytics</a>
						</div>
						
						<div class="row">
							<div class="col-md-12">
								<div class="box-body">
									<table id="bookingDataTable" class="beecabsGrid table table-striped" border="1">
										<thead>
											<tr>
												<th>Booking Ref.</th>
												<th>Booking Date</th>
												<th>Trip Time</th>
												<th>Guest Name</th>
												<th>Room No</th>
												<th>Trip Type</th>
												<th>Vehicle No</th>
												<th>Driver Name</th>
												
												<?php if ($acl->isAllowed($role, 'Admin\Controller\FpsHotelBooking', 'edit')) { ?>
												<th>E</th>
												<?php } ?>
												<?php if ($acl->isAllowed($role, 'Admin\Controller\FpsHotelBooking', 'complete')) { ?>
												<th>C</th>
												<?php } ?>
												
											</tr>
										</thead>
										<tbody>
											<tr>
												<td colspan="12" class="dataTables_empty">Loading data from server</td>
											</tr>
										</tbody>
									</table>
								</div><!-- /.box-body -->
							</div>
						</div>
					</div>
				</div>
			  <!-- /.panel -->
			</div>
		</div>
	</section><!-- /.content -->
<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
	
    $(document).ready(function() {
    oTable=$('#bookingDataTable').dataTable( {
		"bAutoWidth": false,
        "bProcessing": true,
        "bServerSide": true,
		"bLengthChange": false,
		"scrollX": true,
		//"lengthMenu": [[10,20,30,50,-1], [10,20,30,50,"All"]],
		"pageLength": 30,
         "aoColumns": [
		<?php echo $editAction;?>
            ],
		 "columnDefs":[
			{ "width": "8%", "targets": 0 },
			{ "width": "8%", "targets": 1 },
			{ "width": "6%", "targets": 2 },
			{ "width": "10%", "targets": 3 },
			{ "width": "6%", "targets": 4 },
			{ "width": "8%", "targets": 5 },
			{ "width": "10%", "targets": 6 },
			{ "width": "12%", "targets": 7 },
			{ "width": "2%", "targets": 8 },
			{ "width": "2%", "targets": 9 }
		 ],
		"aaSorting": [[ 0, "desc" ]],
        "sAjaxSource": "<?php echo $this->url('fps-hotel-booking',array('action' => 'index')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
			$.ajax({
				"dataType": 'json',
				"type": "POST",
				"url": sSource,
				"data": aoData,
				"success": fnCallback
			});
        }
    } );
	
} );
	
	function completeBooking(bookingId,bookingNo){
		conf=confirm("Are you sure you want complete "+bookingNo+" booking");
		if(conf){
			$.post("<?php echo $this->url('hotel-booking',array('action' => 'complete')); ?>", {bookingId : bookingId,bookingNo:bookingNo },
			function(data){
				if(data){
					oTable.fnDraw();
					alert("Booking completed successfully");
				}
			});
		}
	}
</script>
