<?php
//\Zend\Debug\Debug::dump($result);die;
use Application\Service\CommonService;
$commonService=new CommonService();
if(isset($result['bill']['converted_gst']) && trim($result['bill']['converted_gst'])=='yes')
  {
    if(isset($result['bill']['invoice_date']) && trim($result['bill']['invoice_date'])!=""){
      $result['bill']['invoice_date']=$commonService->humanDateFormat($result['bill']['invoice_date']);
    }
    if(isset($result['bill']['payment_received_date']) && trim($result['bill']['payment_received_date'])!=""){
      $result['bill']['payment_received_date']=$commonService->humanDateFormat($result['bill']['payment_received_date']);
    }
    if(isset($result['bill']['payment_due_date']) && trim($result['bill']['payment_due_date'])!=""){
      $result['bill']['payment_due_date']=$commonService->humanDateFormat($result['bill']['payment_due_date']);
    }
    if(isset($result['bill']['service_tax_type']) && $result['bill']['service_tax_type']=='sgst'){
      $totTax=$result['bill']['sgst_tax']+$result['bill']['cgst_tax'];
    }else{
      $totTax=$result['bill']['igst_tax'];
    }
?>
    <!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Edit </span>
				<span class="pageHeadingLabe12">Monthly Bill</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
          <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
            <li><a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>"> Monthly Billing</a></li>
            <li class="active">Edit Monthly Bill</li>
				</ol>
			</div>
		</div>
  </section>
  
  <section class="content">
      <!-- left column -->
      <div class="row">
          <!-- general form elements -->
          <div class="col-xs-12">
              <div class="box-header">
                  <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
              </div><!-- /.box-header -->
              <!-- form start -->
              <form class="form-horizontal" name="addMonthlyBillInfo" id="addMonthlyBillInfo"  method="post" action="<?php echo $this->url('monthly-billing', array('action' => 'edit')); ?>" autocomplete="off">
                  <div class="box-body">
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="company" class="col-lg-4 control-label">Company <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <select class="form-control isRequired" name="company" id="company" onchange="getClient();getInvoiceNo();">
                                          <option value="">--Select--</option>
                                          <?php
                                          foreach($company as $com){
                                          ?>
                                          <option value="<?php echo $com['company_id'];?>" <?php echo(($com['company_id']==$result['bill']['company_id']) ? "selected='selected'" : "") ?>><?php echo $com['company_name'];?></option>
                                          <?php
                                          }
                                          ?>
                                          
                                      </select>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="businessUnit" class="col-lg-4 control-label">Business Unit <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <select  class="form-control isRequired" id="businessUnit" name="businessUnit" title="Please select business unit">
                                          <option value="">--Select--</option>
                                          <?php
                                          foreach($businessUnit as $val){
                                          ?>
                                          <option value="<?php echo base64_encode($val['unit_id']); ?>" <?php echo(($val['unit_id']==$result['bill']['business_unit']) ? "selected='selected'" : "") ?>><?php echo ucwords($val['unit_name']);  ?></option>
                                          <?php
                                          }
                                          ?>
                                      </select>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="invoiceNo" class="col-lg-4 control-label">Invoice No. <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control isRequired " id="invoiceNo" name="invoiceNo" placeholder="Enter invoice number" title="Please enter invoice number" onblur="checkMultipleFieldValidations()" value="<?php echo $result['bill']['invoice_no']; ?>"/>
                                      <input type="hidden" class="form-control isRequired " id="billId" name="billId" value="<?php echo base64_encode($result['bill']['month_bill_id']); ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label class="col-lg-4 control-label">Invoice Month & Year <span class="mandatory">*</span></label>
                                  <div class="col-lg-6 input-append date" id="dpMonths" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                                      <input type="text" class="form-control isRequired readonly" id="invoiceMonth" name="invoiceMonth" placeholder="Select invoice month & year" title="Please select invoice month and year" readonly="readonly" value="<?php echo $result['bill']['invoice_month_year']; ?>"/>
                                      <span class="add-on"><i class="icon-calendar"></i></span>
                                  </div>
                              </div>
                          </div>
                          
                      </div>
                      
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label class="col-lg-4 control-label">Invoice Date <span class="mandatory">*</span> </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control isRequired readonly" id="invoiceDate" name="invoiceDate" placeholder="Invoice Date" readonly="readonly" title="Please select the invoice date" value="<?php echo $result['bill']['invoice_date']; ?>"/>
                                      <input type="hidden" class="form-control " id="searchInvoiceDate" name="searchInvoiceDate" readonly="readonly" value="<?php echo $result['bill']['search_month_year']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="client" class="col-lg-4 control-label">Client <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <select  class="form-control isRequired" id="client" name="client" title="Please select client" onchange="getServiceTax(this);calTotalAmt();calBalanceAmt();">
                                          <option value="">--Select--</option>
                                      </select>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="subject" class="col-lg-4 control-label">Subject </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control" id="subject" name="subject" placeholder="Enter subject" title="Please enter the subject" value="<?php echo $result['bill']['subject']; ?>"/>
                                      <input type="hidden" id="deletedId" name="deletedId" value="" />
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="usageParticulars" class="col-lg-4 control-label">Usage Particulars </label>
                                  <div class="col-lg-6">
                                      <textarea class="form-control" id="usageParticulars" name="usageParticulars" placeholder="Enter usage particulars" title="Please enter the usage particulars"><?php echo $result['bill']['particulars']; ?></textarea>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="basic" class="col-lg-4 control-label">Basic Particulars <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control isRequired" id="basic" name="basic" placeholder="Enter basic" title="Please enter the basic" value="<?php echo $result['bill']['basic']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="basicAmount" class="col-lg-4 control-label">Basic Amount <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control isRequired checkNum" id="basicAmount" name="basicAmount" placeholder="Enter basic amount" title="Please enter the basic amount" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $result['bill']['basic_amount']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                              <div class="form-group">
                                  <label for="toll" class="col-lg-4 control-label">Toll/Parking </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control checkNum" id="toll" name="toll" placeholder="Enter toll/parking" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $result['bill']['parking_fee']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="driverRetention" class="col-lg-4 control-label">Driver Retention </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control checkNum" id="driverRetention" name="driverRetention" placeholder="Enter driver retention" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $result['bill']['driver_retention']; ?>"/>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group" >
                                  <label class="col-lg-4 control-label">Other Details </label>
                                  <div class="col-lg-8">
                                      <table id="otherDetailsTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" style="width: 100%;">
                                      <thead>
                                      <tr>
                                          <th>Other Name</th>
                                          <th style="width:30%;">Other Amount</th>
                                          <th>Action</th>
                                      </tr>
                                      </thead>
                                      <tbody>
                                        <?php
                                        $i=1;
                                        if(count($result['otherAmount'])>0){
                                          foreach($result['otherAmount'] as $other){
                                        ?>
                                      <tr>
                                          <td>
                                          <input type="text" id="otherName<?php echo $i; ?>" name="otherName[]" class="form-control" placeholder="Other Name" value="<?php echo $other['other_name']; ?>"/>
                                          <input type="hidden" id="otherId<?php echo $i;?>" name="otherId[]" class="form-control" placeholder="" value="<?php echo $other['other_id']; ?>"/>
                                          </td>
                                          <td>
                                          <input type="text" class="form-control otherAmount checkNum" id="otherAmount<?php echo $i; ?>" name="otherAmount[]" placeholder="Other Amount" title="" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $other['other_amount']; ?>"/>
                                          </td>
                                          
                                          <td align="center">
                                          <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="<?php echo $other['other_id']; ?>" onclick="removeRow(this.parentNode.parentNode);countDelete(this.id);"><i class="fa fa-minus"></i></a>
                                          </td>
                                          
                                      </tr>
                                      <?php
                                      $i++;
                                          }
                                      }else{ ?>
                                      <tr>
                                          <td>
                                          <input type="text" id="otherName1" name="otherName[]" class="form-control" placeholder="Other Name"/>
                                          </td>
                                          <td>
                                          <input type="text" class="form-control otherAmount checkNum" id="otherAmount1" name="otherAmount[]" placeholder="Other Amount" title="" onblur="calTotalAmt();calBalanceAmt();"/>
                                          </td>
                                          
                                          <td align="center">
                                          <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                                          </td>
                                          
                                      </tr>
                                      <?php } ?>
                                      </tbody>
                                  </table>
                                  </div>
                              </div>
                          </div>
                         
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="serviceTaxAmount" class="col-lg-4 control-label">Service Tax <span id="serviceTaxSpan">(<?php echo $totTax; ?>%)</span> <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <input type="hidden" class="form-control isRequired" id="serviceTaxType" name="serviceTaxType" value="<?php echo $result['bill']['service_tax_type']; ?>"/>
                                      <input type="hidden" class="form-control" id="sgstTax" name="sgstTax" value="<?php echo $result['bill']['sgst_tax']; ?>"/>
                                      <input type="hidden" class="form-control" id="cgstTax" name="cgstTax" value="<?php echo $result['bill']['cgst_tax']; ?>"/>
                                      <input type="hidden" class="form-control" id="igstTax" name="igstTax" value="<?php echo $result['bill']['igst_tax']; ?>"/>
                                      <input type="hidden" class="form-control" id="calTax" name="calTax" value="<?php echo $totTax; ?>"/>
                                      <input type="text" class="form-control isRequired checkNum readonly" id="serviceTaxAmount" name="serviceTaxAmount" placeholder="Enter service tax" readonly="readonly" value="<?php echo $result['bill']['service_tax_amount']; ?>"/>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="netAmount" class="col-lg-4 control-label">Total Amount </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control checkNum" id="netAmount" name="netAmount" placeholder="Enter total amount" value="<?php echo $result['bill']['net_amount']; ?>"/>
                                      <input type="hidden" class="form-control" id="totalAmount" name="totalAmount" value="<?php echo $result['bill']['total_amount']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label class="col-lg-4 control-label">Payment Due Date <span class="mandatory">*</span> </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control datepicker readonly isRequired" id="paymentDate" name="paymentDate" placeholder="Payment Date" readonly="readonly" title="Please select the payment due date" value="<?php echo $result['bill']['payment_due_date']; ?>"/>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="tds" class="col-lg-4 control-label">TDS </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control checkNum" id="tds" name="tds" placeholder="Enter tds" onblur="calBalanceAmt();" value="<?php echo $result['bill']['tds']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="discount" class="col-lg-4 control-label">Discount </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control checkNum" id="discount" name="discount" placeholder="Enter discount" onblur="calBalanceAmt();" value="<?php echo $result['bill']['discount']; ?>"/>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="receivedAmount" class="col-lg-4 control-label">Received Amount </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control checkNum" id="receivedAmount" name="receivedAmount" placeholder="Enter received amount" title="Please enter the received amount" onblur="calBalanceAmt();" value="<?php echo $result['bill']['received_amount']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="paymentMode" class="col-lg-4 control-label">Payment Mode </label>
                                  <div class="col-lg-6">
                                      <select  class="form-control" id="paymentMode" name="paymentMode" title="Please select payment mode" >
                                          <option value="">--Select--</option>
                                          <?php
                                          foreach($paymentMode as $mode){
                                          ?>
                                          <option value="<?php echo base64_encode($mode['type_id']); ?>" <?php echo(($mode['type_id']==$result['bill']['payment_mode']) ? "selected='selected'" : "") ?>><?php echo $mode['payment_type']; ?></option>
                                          <?php
                                          }
                                          ?>
                                      </select>
                                  </div>
                              </div>
                          </div>
                          
                      </div>
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="invoicePreparedBy" class="col-lg-4 control-label">Invoice Prepared By <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <select class="form-control isRequired" id="invoicePreparedBy" name="invoicePreparedBy" title="Please select invoice prepared by">
                                        <option value="">--Select--</option>
                                        <?php
                                        foreach($employee as $val){
                                        ?>
                                        <option value="<?php echo $val['employee_id']; ?>" <?php echo(($result['bill']['invoice_prepared_by']==$val['employee_id']) ? "selected='selected'" : "") ?>><?php echo ucwords($val['employee_name'])." - ".$val['employee_no']; ?></option>
                                        <?php
                                        }
                                        ?>
                                      </select>
                                  </div>
                              </div>
                          </div>
                          
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label for="remarks" class="col-lg-4 control-label">Remarks </label>
                                  <div class="col-lg-6">
                                      <textarea class="form-control" id="remarks" name="remarks" placeholder="Enter remarks" title="Please enter the remarks"><?php echo $result['bill']['remarks']; ?></textarea>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                              <div class="form-group">
                                  <label for="paymentStatus" class="col-lg-4 control-label">Payment Status <span class="mandatory">*</span></label>
                                  <div class="col-lg-6">
                                      <select class="form-control isRequired" id="paymentStatus" name="paymentStatus" title="Please select payment status">
                                          <option value="">--Select--</option>
                                          <option value="paid" <?php echo(($result['bill']['payment_status']=='paid') ? "selected='selected'" : "") ?>>Paid</option>
                                          <option value="pending" <?php echo(($result['bill']['payment_status']=='pending') ? "selected='selected'" : "") ?>>Pending</option>
                                      </select>
                                  </div>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label class="col-lg-4 control-label">Received Date </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control readonly" id="receivedDate" name="receivedDate" placeholder="Received Date" readonly="readonly" title="Please select the payment received date" value="<?php echo $result['bill']['payment_received_date']; ?>"/>
                                  </div>
                              </div>
                          </div>
                          
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                              <div class="form-group">
                                  <label for="balance" class="col-lg-4 control-label">Balance </label>
                                  <div class="col-lg-6">
                                      <input type="text" class="form-control" id="balance" name="balance" placeholder="Enter balance" value="<?php echo $result['bill']['balance']; ?>"/>
                                  </div>
                              </div>
                          </div>
                      </div>
                      
                      <div class="box-footer">
                          <a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                          <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                      </div>
              </form>
          </div><!-- /.box -->
      </div><!--/.col (left) -->
  </section><!-- /.content -->
  </div>

    <script type="text/javascript">
        duplicateName = true;
        selectedDate="";
        rowCount='<?php echo $i; ?>';
        deletedId=[];
        function validateNow() {
            flag = deforayValidator.init({
                formId: 'addMonthlyBillInfo'
            });
            if (flag) {
                if (duplicateName) {
                  $.blockUI();
                  document.getElementById('addMonthlyBillInfo').submit();
                }
            }
        }
        
        function checkNameValidation(tableName, fieldName, obj, fnct, msg){
            $.blockUI();
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct},
            function(data) {
                if (data > 0)
                {
                    alert(msg);
                    duplicateName = false;
                    document.getElementById('invoiceNo').value = "";
                    $.unblockUI();
                }
                else {
                    duplicateName = true;
                    $.unblockUI();
                }
            });
        }
        
        function checkMultipleFieldValidations()
        {
            companyId=$("#company").val();
            invoiceNo=$("#invoiceNo").val();
            if(companyId!="" && invoiceNo!=""){
            var json_data = { 
              "tableName" : "monthly_billing_details",
              "tablePrimaryKeyId" : "month_bill_id",
              "tablePrimaryKeyValue" : "<?php echo $result['bill']['month_bill_id']; ?>",
              "columns":[
                      {
                          "column_name" : "company_id",
                          "column_value": companyId
                      },
                      {
                          "column_name" : "invoice_no",
                          "column_value": invoiceNo
                      }
              ]
            }
            //console.log(json_data);
            $.post("<?php echo $this->url('common', array('action' => 'check-multiple-column-value')); ?>", { json_data : json_data},
            function(data){
              if(data>0)
              {
                alert("This invoice number already exist,Please enter another number");
                document.getElementById("invoiceNo").value="";
                getInvoiceNo();
                duplicateName=false;
              }
              else{
                duplicateName=true;
              }
            });
             
            }
        }
      
        $(function() {
          $('#invoiceDate').datepicker({
                //todayBtn: "linked",
                clearBtn: true,
                autoclose: true,
                todayHighlight: true,
                format: 'dd-M-yyyy'
          });
            
          $('.datepicker').datepicker({
                //todayBtn: "linked",
                clearBtn: true,
                autoclose: true,
                todayHighlight: true,
                format: 'dd-M-yyyy',
                startDate:'today'
          });
            
          $('#receivedDate').datepicker({
                //todayBtn: "linked",
                clearBtn: true,
                autoclose: true,
                todayHighlight: true,
                format: 'dd-M-yyyy',
                endDate:'today'
          });
            
        $('#dpMonths').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
            format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
        }).on('changeDate', function(e) {
            var date = new Date($('#invoiceMonth').val());
            var day = date.getDate();
            var monthIndex = date.getMonth()+parseInt(1);
            var year = date.getFullYear();
            selectedDate=year+"-"+monthIndex+"-"+day;
            $("#searchInvoiceDate").val(selectedDate);
        });
            getOnloadClient();
      });
        
        function getServiceTax(obj){
            sbcTax=0;
            kkcTax=0;
            selected=obj.options[obj.selectedIndex];
            service_tax_type=selected.getAttribute('data-service-tax-type');
            sgst="";
            cgst="";
            igst="";
            calTax="";
            if(service_tax_type=='sgst'){
                sgst=selected.getAttribute('data-sgst');
                cgst=selected.getAttribute('data-cgst');
                calTax=parseFloat(sgst)+parseFloat(cgst);
                $("#sgstTax").val(sgst);
                $("#cgstTax").val(cgst);
            }else if(service_tax_type=='igst'){
                igst=selected.getAttribute('data-igst');
                calTax=parseFloat(igst);
                $("#igstTax").val(igst);
            }
            if(calTax==0){
						$("#serviceTaxAmount").removeClass("isRequired");;
						}
            $("#serviceTaxType").val(service_tax_type);
            $("#calTax").val(calTax);
            document.getElementById("serviceTaxSpan").innerHTML="("+calTax+"%)";
        }
        
        function calTotalAmt(){
          totAmt=0;
          basicAmount=$("#basicAmount").val();
          serviceTax=$("#calTax").val();
          other=$("#other").val();
          toll=$("#toll").val();
          driverRetention=$("#driverRetention").val();
          $("#netAmount").val();
          discount=$("#discount").val();
          if(basicAmount!=""){
              totAmt=parseFloat(basicAmount);
          }
          if(toll!=""){
              totAmt=parseFloat(totAmt)+parseFloat(toll);
          }
          if(driverRetention!=""){
              totAmt=parseFloat(totAmt)+parseFloat(driverRetention);
          }
          
          $(".otherAmount").each(function() {
            if(this.value>0){
              totAmt=parseFloat(this.value)+parseFloat(totAmt);
            }
          });
          $("#totalAmount").val(totAmt);
          if(basicAmount!="" && serviceTax!=""){
              service_tax=(parseFloat(serviceTax)/100);
              serviceTaxAmt=parseFloat(totAmt*service_tax).toFixed(2);
              $("#serviceTaxAmount").val(serviceTaxAmt);
              totAmt=parseFloat(totAmt)+parseFloat(serviceTaxAmt);
          }
          $("#netAmount").val(totAmt);
        }
        
        function calBalanceAmt(){
            tds=$("#tds").val();
            discount=$("#discount").val();
            receivedAmount=$("#receivedAmount").val();
            totAmt=$("#netAmount").val();
            if(tds!=""){
                totAmt=parseFloat(totAmt)-parseFloat(tds);
            }
            if(discount!=""){
                totAmt=parseFloat(totAmt)-parseFloat(discount);
            }
            if(receivedAmount!=""){
                totAmt=parseFloat(totAmt)-parseFloat(receivedAmount);
            }
            $("#balance").val(totAmt);
        }
        
        function getClient(){
            $.blockUI();
            $.post("<?php echo $this->url('clients', array('action' => 'get-client-by-company')); ?>", {company: $("#company").val()},
            function(data) {
                if (data!="")
                {
                    $("#client").html(data);
										
										$("#client").select2({
											placeholder: "--Select Client--",
											tags: true
										}).on("change", function(e) {
											calTotalAmt();
											calBalanceAmt();
										});
										
                    $.unblockUI();
                }
            });
        }
        
        function getOnloadClient(){
            $.blockUI();
            $.post("<?php echo $this->url('clients', array('action' => 'get-client-by-company')); ?>", {company: $("#company").val()},
            function(data) {
                if (data!="")
                {
                    $("#client").html(data);
                    $.unblockUI();
                    <?php
                    if(isset($result['bill']['client']) && $result['bill']['client']>0){
                    ?>
                    $("#client").val('<?php echo $result['bill']['client']; ?>');
                    <?php
                    }
                    ?>
										$("#client").select2({
											placeholder: "--Select Client--",
											tags: true
										}).on("change", function(e) {
											calTotalAmt();
											calBalanceAmt();
										});
                }
            });
        }
        
        function insRow() {
        rowCount++;
        rl = document.getElementById("otherDetailsTable").rows.length;
        var a = document.getElementById("otherDetailsTable").insertRow(rl);
        a.setAttribute("style", "display:none;");
        a.setAttribute("class", "data");
        var b = a.insertCell(0);
        var c = a.insertCell(1);
        var d = a.insertCell(2);
        
        d.setAttribute("align", "center");
        
        rl = document.getElementById("otherDetailsTable").rows.length - 1;
        b.innerHTML = '<input type="text" class="form-control" id="otherName' + rowCount + '" name="otherName[]" placeholder="Other Name" />';
        c.innerHTML = '<input type="text" class="form-control otherAmount checkNum" id="otherAmount' + rowCount + '" name="otherAmount[]" placeholder="Other Amount" onblur="calTotalAmt();calBalanceAmt();"/>';
        d.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
        $(a).fadeIn(800);
        checkNum();
        }
      
      function removeRow(el) {
        $(el).fadeOut("slow", function() {
            el.parentNode.removeChild(el);
            rl = document.getElementById("otherDetailsTable").rows.length;
            if (rl == 1) {
          insRow();
            }
            calTotalAmt();
            calBalanceAmt();
        });
        }
        
        function countDelete(e){
          deletedId.push(e);
          document.getElementById("deletedId").value=deletedId;
      }
      
      function getInvoiceNo(){
        companyId=$("#company").val();
        if(companyId!=""){
            $.blockUI();
            $.post("<?php echo $this->url('monthly-billing', array('action' => 'get-invoice-no')); ?>", {company: companyId},
            function(data) {
                if (data!="")
                {
                    $("#invoiceNo").val(data+'<?php echo $monthlyInvoiceCode ?>');
                    $.unblockUI();
                }
            });
        }
      }
    </script>
<?php }else
  {
?>
<?php
  if(isset($result['bill']['invoice_date']) && trim($result['bill']['invoice_date'])!=""){
    $result['bill']['invoice_date']=$commonService->humanDateFormat($result['bill']['invoice_date']);
  }
  if(isset($result['bill']['payment_received_date']) && trim($result['bill']['payment_received_date'])!=""){
    $result['bill']['payment_received_date']=$commonService->humanDateFormat($result['bill']['payment_received_date']);
  }
  if(isset($result['bill']['payment_due_date']) && trim($result['bill']['payment_due_date'])!=""){
    $result['bill']['payment_due_date']=$commonService->humanDateFormat($result['bill']['payment_due_date']);
  }
?>
    <!-- Main content -->
    <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>Edit Monthly Bill</h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>"> Monthly Billing</a></li>
            <li class="active">Edit Monthly Bill</li>
          </ol>
        </section>
    <section class="content">
        <!-- left column -->
        <div class="">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header">
                    <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
                </div><!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" name="addMonthlyBillInfo" id="addMonthlyBillInfo"  method="post" action="<?php echo $this->url('monthly-billing', array('action' => 'edit')); ?>" autocomplete="off">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="company" class="col-lg-4 control-label">Company <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <select class="form-control isRequired" name="company" id="company" onchange="getClient();getInvoiceNo();">
                                            <option value="">--Select--</option>
                                            <?php
                                            foreach($company as $com){
                                            ?>
                                            <option value="<?php echo $com['company_id'];?>" <?php echo(($com['company_id']==$result['bill']['company_id']) ? "selected='selected'" : "") ?>><?php echo $com['company_name'];?></option>
                                            <?php
                                            }
                                            ?>
                                            
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="businessUnit" class="col-lg-4 control-label">Business Unit <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <select  class="form-control isRequired" id="businessUnit" name="businessUnit" title="Please select business unit">
                                            <option value="">--Select--</option>
                                            <?php
                                            foreach($businessUnit as $val){
                                            ?>
                                            <option value="<?php echo base64_encode($val['unit_id']); ?>" <?php echo(($val['unit_id']==$result['bill']['business_unit']) ? "selected='selected'" : "") ?>><?php echo ucwords($val['unit_name']);  ?></option>
                                            <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="invoiceNo" class="col-lg-4 control-label">Invoice No. <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control isRequired " id="invoiceNo" name="invoiceNo" placeholder="Enter invoice number" title="Please enter invoice number" onblur="checkMultipleFieldValidations()" value="<?php echo $result['bill']['invoice_no']; ?>"/>
                                        <input type="hidden" class="form-control isRequired " id="billId" name="billId" value="<?php echo base64_encode($result['bill']['month_bill_id']); ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-lg-4 control-label">Invoice Month & Year <span class="mandatory">*</span></label>
                                    <div class="col-lg-6 input-append date" id="dpMonths" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                                        <input type="text" class="form-control isRequired readonly" id="invoiceMonth" name="invoiceMonth" placeholder="Select invoice month & year" title="Please select invoice month and year" readonly="readonly" value="<?php echo $result['bill']['invoice_month_year']; ?>"/>
                                        <span class="add-on"><i class="icon-calendar"></i></span>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-lg-4 control-label">Invoice Date <span class="mandatory">*</span> </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control isRequired readonly" id="invoiceDate" name="invoiceDate" placeholder="Invoice Date" readonly="readonly" title="Please select the invoice date" value="<?php echo $result['bill']['invoice_date']; ?>"/>
                                        <input type="hidden" class="form-control " id="searchInvoiceDate" name="searchInvoiceDate" readonly="readonly" value="<?php echo $result['bill']['search_month_year']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="client" class="col-lg-4 control-label">Client <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <select  class="form-control isRequired" id="client" name="client" title="Please select client" onchange="getServiceTax(this);calTotalAmt();calBalanceAmt();">
                                            <option value="">--Select--</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="subject" class="col-lg-4 control-label">Subject </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control" id="subject" name="subject" placeholder="Enter subject" title="Please enter the subject" value="<?php echo $result['bill']['subject']; ?>"/>
                                        <input type="hidden" id="deletedId" name="deletedId" value="" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="usageParticulars" class="col-lg-4 control-label">Usage Particulars </label>
                                    <div class="col-lg-6">
                                        <textarea class="form-control" id="usageParticulars" name="usageParticulars" placeholder="Enter usage particulars" title="Please enter the usage particulars"><?php echo $result['bill']['particulars']; ?></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="basic" class="col-lg-4 control-label">Basic Particulars <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control isRequired" id="basic" name="basic" placeholder="Enter basic" title="Please enter the basic" value="<?php echo $result['bill']['basic']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="basicAmount" class="col-lg-4 control-label">Basic Amount <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control isRequired checkNum" id="basicAmount" name="basicAmount" placeholder="Enter basic amount" title="Please enter the basic amount" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $result['bill']['basic_amount']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div class="row">
                          <div class="col-md-6">
                                <div class="form-group">
                                    <label for="toll" class="col-lg-4 control-label">Toll/Parking </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control checkNum" id="toll" name="toll" placeholder="Enter toll/parking" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $result['bill']['parking_fee']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="driverRetention" class="col-lg-4 control-label">Driver Retention </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control checkNum" id="driverRetention" name="driverRetention" placeholder="Enter driver retention" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $result['bill']['driver_retention']; ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group" >
                                    <label class="col-lg-4 control-label">Other Details </label>
                                    <div class="col-lg-8">
                                        <table id="otherDetailsTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" style="width: 100%;">
                                        <thead>
                                        <tr>
                                            <th>Other Name</th>
                                            <th style="width:30%;">Other Amount</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                          <?php
                                          $i=1;
                                          if(count($result['otherAmount'])>0){
                                            foreach($result['otherAmount'] as $other){
                                          ?>
                                        <tr>
                                            <td>
                                            <input type="text" id="otherName<?php echo $i; ?>" name="otherName[]" class="form-control" placeholder="Other Name" value="<?php echo $other['other_name']; ?>"/>
                                            <input type="hidden" id="otherId<?php echo $i;?>" name="otherId[]" class="form-control" placeholder="" value="<?php echo $other['other_id']; ?>"/>
                                            </td>
                                            <td>
                                            <input type="text" class="form-control otherAmount checkNum" id="otherAmount<?php echo $i; ?>" name="otherAmount[]" placeholder="Other Amount" title="" onblur="calTotalAmt();calBalanceAmt();" value="<?php echo $other['other_amount']; ?>"/>
                                            </td>
                                            
                                            <td align="center">
                                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="<?php echo $other['other_id']; ?>" onclick="removeRow(this.parentNode.parentNode);countDelete(this.id);"><i class="fa fa-minus"></i></a>
                                            </td>
                                            
                                        </tr>
                                        <?php
                                        $i++;
                                            }
                                        }else{ ?>
                                        <tr>
                                            <td>
                                            <input type="text" id="otherName1" name="otherName[]" class="form-control" placeholder="Other Name"/>
                                            </td>
                                            <td>
                                            <input type="text" class="form-control otherAmount checkNum" id="otherAmount1" name="otherAmount[]" placeholder="Other Amount" title="" onblur="calTotalAmt();calBalanceAmt();"/>
                                            </td>
                                            
                                            <td align="center">
                                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                                            </td>
                                            
                                        </tr>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                    </div>
                                </div>
                            </div>
                           
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="serviceTaxAmount" class="col-lg-4 control-label">Service Tax <span id="serviceTaxSpan">(<?php echo $result['bill']['service_tax']+$result['bill']['sbc_tax']+$result['bill']['kkc_tax']; ?>%)</span> <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <input type="hidden" class="form-control isRequired" id="serviceTax" name="serviceTax" value="<?php echo $result['bill']['service_tax']; ?>"/>
                                        <input type="hidden" class="form-control" id="sbcTax" name="sbcTax" value="<?php echo $result['bill']['sbc_tax']; ?>"/>
                                        <input type="hidden" class="form-control" id="kkcTax" name="kkcTax" value="<?php echo $result['bill']['kkc_tax']; ?>"/>
                                        <input type="text" class="form-control isRequired checkNum readonly" id="serviceTaxAmount" name="serviceTaxAmount" placeholder="Enter service tax" readonly="readonly" value="<?php echo $result['bill']['service_tax_amount']; ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="netAmount" class="col-lg-4 control-label">Total Amount </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control checkNum" id="netAmount" name="netAmount" placeholder="Enter total amount" value="<?php echo $result['bill']['net_amount']; ?>"/>
                                        <input type="hidden" class="form-control" id="totalAmount" name="totalAmount" value="<?php echo $result['bill']['total_amount']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-lg-4 control-label">Payment Due Date <span class="mandatory">*</span> </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control datepicker readonly isRequired" id="paymentDate" name="paymentDate" placeholder="Payment Date" readonly="readonly" title="Please select the payment due date" value="<?php echo $result['bill']['payment_due_date']; ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="tds" class="col-lg-4 control-label">TDS </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control checkNum" id="tds" name="tds" placeholder="Enter tds" onblur="calBalanceAmt();" value="<?php echo $result['bill']['tds']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="discount" class="col-lg-4 control-label">Discount </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control checkNum" id="discount" name="discount" placeholder="Enter discount" onblur="calBalanceAmt();" value="<?php echo $result['bill']['discount']; ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="receivedAmount" class="col-lg-4 control-label">Received Amount </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control checkNum" id="receivedAmount" name="receivedAmount" placeholder="Enter received amount" title="Please enter the received amount" onblur="calBalanceAmt();" value="<?php echo $result['bill']['received_amount']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="paymentMode" class="col-lg-4 control-label">Payment Mode </label>
                                    <div class="col-lg-6">
                                        <select  class="form-control" id="paymentMode" name="paymentMode" title="Please select payment mode" >
                                            <option value="">--Select--</option>
                                            <?php
                                            foreach($paymentMode as $mode){
                                            ?>
                                            <option value="<?php echo base64_encode($mode['type_id']); ?>" <?php echo(($mode['type_id']==$result['bill']['payment_mode']) ? "selected='selected'" : "") ?>><?php echo $mode['payment_type']; ?></option>
                                            <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="invoicePreparedBy" class="col-lg-4 control-label">Invoice Prepared By <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <select class="form-control isRequired" id="invoicePreparedBy" name="invoicePreparedBy" title="Please select invoice prepared by">
                                          <option value="">--Select--</option>
                                          <?php
                                          foreach($employee as $val){
                                          ?>
                                          <option value="<?php echo $val['employee_id']; ?>" <?php echo(($result['bill']['invoice_prepared_by']==$val['employee_id']) ? "selected='selected'" : "") ?>><?php echo ucwords($val['employee_name'])." - ".$val['employee_no']; ?></option>
                                          <?php
                                          }
                                          ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="remarks" class="col-lg-4 control-label">Remarks </label>
                                    <div class="col-lg-6">
                                        <textarea class="form-control" id="remarks" name="remarks" placeholder="Enter remarks" title="Please enter the remarks"><?php echo $result['bill']['remarks']; ?></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                          <div class="col-md-6">
                                <div class="form-group">
                                    <label for="paymentStatus" class="col-lg-4 control-label">Payment Status <span class="mandatory">*</span></label>
                                    <div class="col-lg-6">
                                        <select class="form-control isRequired" id="paymentStatus" name="paymentStatus" title="Please select payment status">
                                            <option value="">--Select--</option>
                                            <option value="paid" <?php echo(($result['bill']['payment_status']=='paid') ? "selected='selected'" : "") ?>>Paid</option>
                                            <option value="pending" <?php echo(($result['bill']['payment_status']=='pending') ? "selected='selected'" : "") ?>>Pending</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-lg-4 control-label">Received Date </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control readonly" id="receivedDate" name="receivedDate" placeholder="Received Date" readonly="readonly" title="Please select the payment received date" value="<?php echo $result['bill']['payment_received_date']; ?>"/>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div class="row">
                          <div class="col-md-6">
                                <div class="form-group">
                                    <label for="balance" class="col-lg-4 control-label">Balance </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control" id="balance" name="balance" placeholder="Enter balance" value="<?php echo $result['bill']['balance']; ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="box-footer">
                            <input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();return false;">
                            <a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                        </div>
                </form>
            </div><!-- /.box -->
        </div><!--/.col (left) -->
    </section><!-- /.content -->

    <script type="text/javascript">
        duplicateName = true;
        selectedDate="";
        rowCount='<?php echo $i; ?>';
        deletedId=[];
        function validateNow() {
    
            flag = deforayValidator.init({
                formId: 'addMonthlyBillInfo'
            });
            if (flag) {
                if (duplicateName) {
                  document.getElementById('addMonthlyBillInfo').submit();
                }
            }
        }
        
        function checkNameValidation(tableName, fieldName, obj, fnct, msg){
            $.blockUI();
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.value, fnct: fnct},
            function(data) {
                if (data > 0)
                {
                    alert(msg);
                    duplicateName = false;
                    document.getElementById('invoiceNo').value = "";
                    $.unblockUI();
                }
                else {
                    duplicateName = true;
                    $.unblockUI();
                }
            });
        }
        
        function checkMultipleFieldValidations()
        {
            companyId=$("#company").val();
            invoiceNo=$("#invoiceNo").val();
            if(companyId!="" && invoiceNo!=""){
            var json_data = { 
              "tableName" : "monthly_billing_details",
              "tablePrimaryKeyId" : "month_bill_id",
              "tablePrimaryKeyValue" : "<?php echo $result['bill']['month_bill_id']; ?>",
              "columns":[
                      {
                          "column_name" : "company_id",
                          "column_value": companyId
                      },
                      {
                          "column_name" : "invoice_no",
                          "column_value": invoiceNo
                      }
              ]
            }
            //console.log(json_data);
            $.post("<?php echo $this->url('common', array('action' => 'check-multiple-column-value')); ?>", { json_data : json_data},
            function(data){
              if(data>0)
              {
                alert("This invoice number already exist,Please enter another number");
                document.getElementById("invoiceNo").value="";
                getInvoiceNo();
                duplicateName=false;
              }
              else{
                duplicateName=true;
              }
            });
             
            }
        }
      
        $(function() {
            $('#invoiceDate').datepicker({
                //todayBtn: "linked",
                clearBtn: true,
                autoclose: true,
                todayHighlight: true,
          format: 'dd-M-yyyy'
        });
            
            $('.datepicker').datepicker({
                //todayBtn: "linked",
                clearBtn: true,
                autoclose: true,
                todayHighlight: true,
                format: 'dd-M-yyyy',
                startDate:'today'
        });
            
            $('#receivedDate').datepicker({
                //todayBtn: "linked",
                clearBtn: true,
                autoclose: true,
                todayHighlight: true,
                format: 'dd-M-yyyy',
                endDate:'today'
        });
            
        $('#dpMonths').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
            format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
        }).on('changeDate', function(e) {
            var date = new Date($('#invoiceMonth').val());
            var day = date.getDate();
            var monthIndex = date.getMonth()+parseInt(1);
            var year = date.getFullYear();
            selectedDate=year+"-"+monthIndex+"-"+day;
            $("#searchInvoiceDate").val(selectedDate);
        });
            getOnloadClient();
      });
        
        function getServiceTax(obj){
            sbcTax=0;
            kkcTax=0;
            selected=obj.options[obj.selectedIndex];
            serviceTax=selected.getAttribute('data-service-tax');
            if(selected.getAttribute('data-sbc-tax')!=""){
                sbcTax=selected.getAttribute('data-sbc-tax');
            }
            if(selected.getAttribute('data-kkc-tax')!=""){
                kkcTax=selected.getAttribute('data-kkc-tax');
            }
            calTax=parseFloat(serviceTax)+parseFloat(sbcTax)+parseFloat(kkcTax);
            $("#serviceTax").val(serviceTax);
            $("#sbcTax").val(sbcTax);
            $("#kkcTax").val(kkcTax);
            document.getElementById("serviceTaxSpan").innerHTML="("+calTax+"%)";
        }
        
        function calTotalAmt(){
            totAmt=0;
            sbc_tax=0;
            kkc_tax=0;
            sbcTaxAmt=0;
            kkcTaxAmt=0;
            basicAmount=$("#basicAmount").val();
            serviceTax=$("#serviceTax").val();
            sbcTax=$("#sbcTax").val();
            kkcTax=$("#kkcTax").val();
            other=$("#other").val();
            toll=$("#toll").val();
            driverRetention=$("#driverRetention").val();
            $("#netAmount").val();
            discount=$("#discount").val();
            if(basicAmount!=""){
                totAmt=parseFloat(basicAmount);
            }
            
            if(toll!=""){
                totAmt=parseFloat(totAmt)+parseFloat(toll);
            }
            if(driverRetention!=""){
                totAmt=parseFloat(totAmt)+parseFloat(driverRetention);
            }
            
            $(".otherAmount").each(function() {
              if(this.value>0){
                totAmt=parseFloat(this.value)+parseFloat(totAmt);
              }
            });
            $("#totalAmount").val(totAmt);
            if(sbcTax!=""){
                sbc_tax=(parseFloat(sbcTax)/100);
                sbcTaxAmt=parseFloat(totAmt*sbc_tax).toFixed(2);
            }
            if(kkcTax!=""){
                kkc_tax=(parseFloat(kkcTax)/100);
                kkcTaxAmt=parseFloat(totAmt*kkc_tax).toFixed(2);
            }
            if(basicAmount!="" && serviceTax!=""){
                service_tax=(parseFloat(serviceTax)/100);
                serviceTaxAmt=parseFloat(totAmt*service_tax).toFixed(2);
                taxAmt=(parseFloat(serviceTaxAmt)+parseFloat(sbcTaxAmt)+parseFloat(kkcTaxAmt)).toFixed(2);
                $("#serviceTaxAmount").val(taxAmt);
                totAmt=parseFloat(totAmt)+parseFloat(taxAmt);
            }
            
            $("#netAmount").val(totAmt);
        }
        
        function calBalanceAmt(){
            tds=$("#tds").val();
            discount=$("#discount").val();
            receivedAmount=$("#receivedAmount").val();
            totAmt=$("#netAmount").val();
            if(tds!=""){
                totAmt=parseFloat(totAmt)-parseFloat(tds);
            }
            if(discount!=""){
                totAmt=parseFloat(totAmt)-parseFloat(discount);
            }
            if(receivedAmount!=""){
                totAmt=parseFloat(totAmt)-parseFloat(receivedAmount);
            }
            $("#balance").val(totAmt);
        }
        
        function getClient(){
            $.blockUI();
            $.post("<?php echo $this->url('clients', array('action' => 'get-client-by-company')); ?>", {company: $("#company").val()},
            function(data) {
                if (data!="")
                {
                    $("#client").html(data);
                    $.unblockUI();
                }
            });
        }
        
        function getOnloadClient(){
            $.blockUI();
            $.post("<?php echo $this->url('clients', array('action' => 'get-client-by-company')); ?>", {company: $("#company").val()},
            function(data) {
                if (data!="")
                {
                    $("#client").html(data);
                    $.unblockUI();
                    <?php
                    if(isset($result['bill']['client']) && $result['bill']['client']>0){
                    ?>
                    $("#client").val('<?php echo $result['bill']['client']; ?>');
                    <?php
                    }
                    ?>
                }
            });
        }
        
        function insRow() {
        rowCount++;
        rl = document.getElementById("otherDetailsTable").rows.length;
        var a = document.getElementById("otherDetailsTable").insertRow(rl);
        a.setAttribute("style", "display:none;");
        a.setAttribute("class", "data");
        var b = a.insertCell(0);
        var c = a.insertCell(1);
        var d = a.insertCell(2);
        
        d.setAttribute("align", "center");
        
        rl = document.getElementById("otherDetailsTable").rows.length - 1;
        b.innerHTML = '<input type="text" class="form-control" id="otherName' + rowCount + '" name="otherName[]" placeholder="Other Name" />';
        c.innerHTML = '<input type="text" class="form-control otherAmount checkNum" id="otherAmount' + rowCount + '" name="otherAmount[]" placeholder="Other Amount" onblur="calTotalAmt();calBalanceAmt();"/>';
        d.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
        $(a).fadeIn(800);
        checkNum();
        }
      
      function removeRow(el) {
        $(el).fadeOut("slow", function() {
            el.parentNode.removeChild(el);
            rl = document.getElementById("otherDetailsTable").rows.length;
            if (rl == 1) {
          insRow();
            }
            calTotalAmt();
            calBalanceAmt();
        });
        }
        
        function countDelete(e){
          deletedId.push(e);
          document.getElementById("deletedId").value=deletedId;
      }
      
      function getInvoiceNo(){
        companyId=$("#company").val();
        if(companyId!=""){
            $.blockUI();
            $.post("<?php echo $this->url('monthly-billing', array('action' => 'get-invoice-no')); ?>", {company: companyId},
            function(data) {
                if (data!="")
                {
                    $("#invoiceNo").val(data+'<?php echo $monthlyInvoiceCode ?>');
                    $.unblockUI();
                }
            });
        }
      }
    </script>
<?php } ?>