<?php
use Application\Service\CommonService;
$commonService=new CommonService();
if(isset($result['bill']['invoice_date']) && trim($result['bill']['invoice_date'])!=""){
  $result['bill']['invoice_date']=$commonService->humanDateFormat($result['bill']['invoice_date']);
}
if(isset($result['bill']['payment_received_date']) && trim($result['bill']['payment_received_date'])!=""){
  $result['bill']['payment_received_date']=$commonService->humanDateFormat($result['bill']['payment_received_date']);
}
if(isset($result['bill']['payment_due_date']) && trim($result['bill']['payment_due_date'])!=""){
  $result['bill']['payment_due_date']=$commonService->humanDateFormat($result['bill']['payment_due_date']);
}
?>
     <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>View Monthly Bill</h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>"> Monthly Billing</a></li>
        <li class="active">View Monthly Bill</li>
      </ol>
    </section>
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" autocomplete="off">
                <div class="box-body">
                  <table class="table table-striped table-bordered table-condensed" align="center" style="width: 60%;">
                    <thead>
                      <tr>
                          <th colspan="2" style="text-align: center;" class="bg-aqua">Monthly Bill Details</th>
                      </tr>
                    </thead>
                    <tr>
                      <th style="width: 20%;">Company</th>
                      <td><?php echo $result['bill']['company_name']; ?></td>
                    </tr>
                    <tr>
                      <th>Business Unit</th>
                      <td><?php echo $result['bill']['unit_name']; ?></td>
                    </tr>
                    <tr>
                      <th>Invoice No.</th>
                      <td><?php echo $result['bill']['invoice_no']; ?></td>
                    </tr>
                    <tr>
                      <th>Invoice Date</th>
                      <td><?php echo $result['bill']['invoice_date']; ?></td>
                    </tr>
                    <tr>
                      <th>Client</th>
                      <td><?php echo $result['bill']['client_name']; ?></td>
                    </tr>
                    <tr>
                      <th>Subject</th>
                      <td><?php echo $result['bill']['subject']; ?></td>
                    </tr>
                    <tr>
                      <th>Usage Particulars</th>
                      <td><?php echo $result['bill']['particulars']; ?></td>
                    </tr>
                    <tr>
                      <th>Basic Particulars</th>
                      <td><?php echo $result['bill']['basic']; ?></td>
                    </tr>
                    <tr>
                      <th>Basic Amount</th>
                      <td><?php echo $result['bill']['basic_amount']; ?></td>
                    </tr>
                    <tr>
                      <th>Toll/Parking</th>
                      <td><?php echo $result['bill']['parking_fee']; ?></td>
                    </tr>
                    <tr>
                      <th>Driver Retention</th>
                      <td><?php echo $result['bill']['driver_retention']; ?></td>
                    </tr>
                    <?php
                    if(count($result['otherAmount'])>0){
                      foreach($result['otherAmount'] as $other){
                    ?>
                    <tr>
                        <th>
                          <?php echo $other['other_name']; ?>
                        </th>
                        <td>
                          <?php echo $other['other_amount']; ?>
                        </td>
                    </tr>
                    <?php
                      }
                    }
                    ?>
                    <tr>
                      <th>Service Tax<span id="serviceTaxSpan">(<?php echo $result['bill']['service_tax']+$result['bill']['sbc_tax']+$result['bill']['kkc_tax']; ?>%)</span> </th>
                      <td><?php echo $result['bill']['service_tax_amount']; ?></td>
                    </tr>
                    <tr>
                      <th>Total Amount</th>
                      <td><?php echo $result['bill']['net_amount']; ?></td>
                    </tr>
                    <tr>
                      <th>Payment Due Date</th>
                      <td><?php echo $result['bill']['payment_due_date']; ?></td>
                    </tr>
                    <tr>
                      <th>TDS</th>
                      <td><?php echo $result['bill']['tds']; ?></td>
                    </tr>
                    <tr>
                      <th>Discount</th>
                      <td><?php echo $result['bill']['discount']; ?></td>
                    </tr>
                    <tr>
                      <th>Received Amount</th>
                      <td><?php echo $result['bill']['received_amount']; ?></td>
                    </tr>
                    <tr>
                      <th>Payment Mode</th>
                      <td><?php echo $result['bill']['payment_type']; ?></td>
                    </tr>
                    <tr>
                      <th>Invoice Prepared By</th>
                      <td><?php echo $result['bill']['invoicePreparedBy']; ?></td>
                    </tr>
                    <tr>
                      <th>Remarks</th>
                      <td><?php echo $result['bill']['remarks']; ?></td>
                    </tr>
                    <tr>
                      <th>Payment Status</th>
                      <td><?php echo ucwords($result['bill']['payment_status']); ?></td>
                    </tr>
                    <tr>
                      <th>Received Date</th>
                      <td><?php echo $result['bill']['payment_received_date']; ?></td>
                    </tr>
                    <tr>
                      <th>Balance</th>
                      <td><?php echo $result['bill']['balance']; ?></td>
                    </tr>
                    
                  </table>
                  <br/>
                  <div class="box-footer">
                      <a href="<?php echo $this->url('monthly-billing', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                  </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
   
</script>
