    <!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Add </span>
				<span class="pageHeadingLabe12"> Client</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('clients', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
					<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                 <li><a href="<?php echo $this->url('clients', array('action' => 'index')); ?>"> Clients</a></li>
				<li class="active">Add Client</li>
				</ol>
			</div>
		</div>
  </section>
<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="addVendorInformation" id="addVendorInformation"  method="post" action="<?php echo $this->url('clients', array('action' => 'add')); ?>" enctype="multipart/form-data" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="companyName" class="col-lg-4 control-label">Company <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select  class="form-control isRequired" id="companyName" name="companyName" title="Please select company">
                                        <option value="">--Select--</option>
                                        <?php
                                        foreach($company as $val){
                                        ?>
                                        <option value="<?php echo base64_encode($val['company_id']);  ?>" ><?php echo ucwords($val['company_name']); ?></option>
                                        <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="vendorName" class="col-lg-4 control-label">Client Name <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="vendorName" name="vendorName" placeholder="Client Name" title="Please enter client name" onblur="checkNameValidation('clients','client_name', this, null, 'Already exist this client name . Please enter another name.');"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="clientCode" class="col-lg-4 control-label">Client Code <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="clientCode" name="clientCode" placeholder="Client Code" title="Please enter client code" value="<?php echo "CC".$clientNo ?>" onblur="checkNameValidation('clients','client_no', this, null, 'Already exist this client code . Please enter another code.');"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="address" class="col-lg-4 control-label">Address <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <textarea class="form-control isRequired" name="address" id="address" placeholder="Address" title="Please enter the address"></textarea>
                                </div>
                            </div>
                        </div>
					</div>
					<div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="gstNo" class="col-lg-4 control-label">GST No. <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="gstNo" name="gstNo" placeholder="GST No" title="Please enter GST number"/>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                          <div class="form-group">
                              <label for="panNo" class="col-lg-4 control-label">Pan No. <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired" id="panNo" name="panNo" placeholder="Pan number" title="Please enter pan number"/>
                              </div>
                          </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="clientCity" class="col-lg-4 control-label">City <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="clientCity" name="clientCity" placeholder="Client city" title="Please enter client city"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                              <label for="pincode" class="col-lg-4 control-label">Pincode <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired" id="pincode" name="pincode" placeholder="Enter pincode" title="Please enter pincode"/>
                              </div>
                          </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTaxType" class="col-lg-4 control-label">Tax Type <span class="mandatory">*</span> </label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" id="serviceTaxType" name="serviceTaxType" title="Please select service tax type" onchange="checkServiceType()">
										<option value="">--Select--</option>
										<option value="igst">IGST</option>
                                        <option value="sgst">SGST</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group" style="margin-left:100px;display:none;" id="sgstDiv">
                                <table>
									<tr>
										<td style="width:4%"><label class="col-lg-4 control-label">CGST(%)<span class="mandatory">*</span></label></td>
										<td style="width:12%">
											<input type="text" class="form-control checkNum" id="cgstTax" name="cgstTax" placeholder="CGST" title="Please enter the CGST" />
										</td>
										<td style="width:4%"><label class="col-lg-4 control-label">SGST(%)<span class="mandatory">*</span></label></td>
										<td style="width:26%">
											<input type="text" class="form-control checkNum" id="sgstTax" name="sgstTax" placeholder="SGST" title="Please enter the SGST" style="width:50%"/>
										</td>
									</tr>
								</table>
                            </div>
							<div class="form-group" style="display:none;" id="igstDiv">
                                <label for="igstTax" class="col-lg-4 control-label">IGST (%)</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum" id="igstTax" name="igstTax" placeholder="IGST" title="Please enter the IGST"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                       
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Contract Expiry Date <span class="mandatory">*</span> </label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control datepicker readonly isRequired" id="contractExpDate" name="contractExpDate" placeholder="Contract Expiry Date" title="Please select contract expiry date" readonly="readonly"/>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTaxPaidByClient" class="col-lg-4 control-label">Service Tax Paid By Client <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" id="serviceTaxPaidByClient" name="serviceTaxPaidByClient">
                                        <option value="yes">Yes</option>
                                        <option value="no">No</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTax" class="col-lg-4 control-label">Contract Copy </label>
                                <div class="col-lg-6">
                                    <input type="file" class="form-control" title="please choose file" name="file" id="file">
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                          <div class="form-group">
                              <label for="stateCode" class="col-lg-4 control-label">State Code <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired checkNum" id="stateCode" name="stateCode" placeholder="Enter state code" title="Please enter state code" value=""/>
                              </div>
                          </div>
                        </div>
                    </div>
                    <div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" id="status" name="status" title="Please select status">
                                        <option value="active">Active</option>
                                        <option value="inactive">Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <h4>Contact Details</h4>
                    <table id="bookedByTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>Contact Name</th>
                            <th>Phone No</th>
                            <th>Mobile No</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                            <input type="text" id="contactName1" name="contactName[]" class="form-control" placeholder="Contact Name"/>
                            </td>
                            <td>
                            <input type="text" class="form-control" id="phoneNo1" name="phoneNo[]" placeholder="Phone No" title=""/>
                            </td>
                            <td><input type="text" class="form-control" id="mobileNo1" name="mobileNo[]" placeholder="Mobile No" /></td>
                            <td><input type="text" class="form-control isEmail" id="email1" name="email[]" placeholder="Email" /></td>
                            <td align="center">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                            </td>
                            
                        </tr>
                        </tbody>
                    </table>
                    <!--
                    <h4>Guest Details</h4>
                    <table id="travellerTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>Guest Name</th>
                            <th>Mobile No</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                            <input type="text" id="travellerName1" name="travellerName[]" class="form-control" placeholder="Guest Name"/>
                            </td>
                            <td>
                            <input type="text" class="form-control" id="traMobileNo1" name="traMobileNo[]" placeholder="Mobile No" />
                            </td>
                            <td>
                                <input type="text" class="form-control isEmail" id="traEmail1" name="traEmail[]" placeholder="Email" />
                            </td>
                            <td align="center" style="vertical-align: middle;">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insTravellerRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeTravellerRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                            </td>
                            
                        </tr>
                        </tbody>
                    </table>
                    -->
                    <div class="box-footer">
                        <a href="<?php echo $this->url('clients', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
						<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    rowCount=1;
	traRowCount=1;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addVendorInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('addVendorInformation').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
    
    function insRow() {
		rowCount++;
		rl = document.getElementById("bookedByTable").rows.length;
		var a = document.getElementById("bookedByTable").insertRow(rl);
		a.setAttribute("style", "display:none;");
		a.setAttribute("class", "data");
		var b = a.insertCell(0);
		var c = a.insertCell(1);
		var d = a.insertCell(2);
		var e = a.insertCell(3);
		var f = a.insertCell(4);
		
		f.setAttribute("align", "center");
		
		rl = document.getElementById("bookedByTable").rows.length - 1;
		b.innerHTML = '<input type="text" class="form-control" id="contactName' + rowCount + '" name="contactName[]" placeholder="Contact Name" />';
		c.innerHTML = '<input type="text" class="form-control" id="phoneNo' + rowCount + '" name="phoneNo[]" placeholder="Phone No" />';
		d.innerHTML = '<input type="text" class="form-control" id="mobileNo' + rowCount + '" name="mobileNo[]" placeholder="Mobile No"/>';
		e.innerHTML = '<input type="text" class="form-control isEmail" id="email' + rowCount + '" name="email[]" placeholder="Email"/>';
		f.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
		$(a).fadeIn(800);
    }
	
	function removeRow(el) {
		$(el).fadeOut("slow", function() {
		    el.parentNode.removeChild(el);
		    rl = document.getElementById("bookedByTable").rows.length;
		    if (rl == 1) {
			insRow();
		    }
		});
    }
	function insTravellerRow() {
		traRowCount++;
		rl = document.getElementById("travellerTable").rows.length;
		var a = document.getElementById("travellerTable").insertRow(rl);
		a.setAttribute("style", "display:none;");
		a.setAttribute("class", "data");
		var b = a.insertCell(0);
		var c = a.insertCell(1);
		var d = a.insertCell(2);
		var e = a.insertCell(3);
		
		e.setAttribute("align", "center");
		e.setAttribute("style", "vertical-align: middle;");
		
		rl = document.getElementById("travellerTable").rows.length - 1;
		b.innerHTML = '<input type="text" class="form-control" id="travellerName' + traRowCount + '" name="travellerName[]" placeholder="Guest Name" />';
		c.innerHTML = '<input type="text" class="form-control" id="traMobileNo' + traRowCount + '" name="traMobileNo[]" placeholder="Mobile No" />';
		d.innerHTML = '<input type="text" class="form-control isEmail" id="traEmail' + traRowCount + '" name="traEmail[]" placeholder="Email" />';
		e.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insTravellerRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeTravellerRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
		$(a).fadeIn(800);
    }
	
	function removeTravellerRow(el) {
		$(el).fadeOut("slow", function() {
		    el.parentNode.removeChild(el);
		    rl = document.getElementById("travellerTable").rows.length;
		    if (rl == 1) {
			insTravellerRow();
		    }
		});
    }
    
   
    $(function() {
		$('.datepicker').datepicker({
            //todayBtn: "linked",
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
			format: 'dd-M-yyyy'
		});
	});
	
	function checkServiceType(){
		if($("#serviceTaxType").val()=='sgst'){
			$("#cgstTax").addClass('isRequired');
			$("#sgstTax").addClass('isRequired');
			$("#igstTax").removeClass('isRequired');
			$("#sgstDiv").css('display','block');
			$("#igstDiv").css('display','none');
		}else{
			$("#sgstDiv").css('display','none');
			$("#igstDiv").css('display','block');
			$("#cgstTax").removeClass('isRequired');
			$("#sgstTax").removeClass('isRequired');
			$("#igstTax").addClass('isRequired');
		}
	}
</script>