<?php
use Application\Service\CommonService;
$commonService=new CommonService();
$contExpiryDate="";
$pathname = UPLOAD_PATH . DIRECTORY_SEPARATOR . "clients" . DIRECTORY_SEPARATOR .$result['vendor']['client_id'];
if(isset($result['vendor']['contract_exp_date']) && trim($result['vendor']['contract_exp_date'])!=""){
	$contExpiryDate=$commonService->humanDateFormat($result['vendor']['contract_exp_date']);
}
?>
<!-- Content Header (Page header) -->
  <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" >
				<span class="pageHeadingLabel1">Edit </span>
				<span class="pageHeadingLabe12"> Client</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					<a href="<?php echo $this->url('clients', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
					<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<ol class="breadcrumb">
                 <li><a href="<?php echo $this->url('clients', array('action' => 'index')); ?>"> Clients</a></li>
				<li class="active">Edit Client</li>
				</ol>
			</div>
		</div>
  </section>
<section class="content">
    <!-- left column -->
    <div class="row">
        <!-- general form elements -->
        <div class="col-xs-12">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="editVendorInformation" id="editVendorInformation"  method="post" action="<?php echo $this->url('clients', array('action' => 'edit')); ?>" enctype="multipart/form-data" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="companyName" class="col-lg-4 control-label">Company <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select  class="form-control isRequired" id="companyName" name="companyName" title="Please select company">
                                        <option value="">--Select--</option>
                                        <?php
                                        foreach($company as $val){
                                        ?>
                                        <option value="<?php echo base64_encode($val['company_id']); ?>" <?php echo(($result['vendor']['company_id']==$val['company_id']) ? "selected='selected'" : "") ?>><?php echo ucwords($val['company_name']); ?></option>
                                        <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="vendorName" class="col-lg-4 control-label">Client Name <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="vendorName" name="vendorName" placeholder="Client Name" title="Please enter client name" onblur="checkNameValidation('clients','client_name', this,'<?php echo "client_id##" .$result['vendor']['client_id']; ?>', 'Already exist this client name . Please enter another name.');" value="<?php echo $result['vendor']['client_name']; ?>"/>
									<input type="hidden" class="form-control isRequired" id="vendorId" name="vendorId" placeholder="" value="<?php echo base64_encode($result['vendor']['client_id']); ?>"/>
									<input type="hidden" id="deletedId" name="deletedId" value="" />
									<input type="hidden" id="deletedTravellerId" name="deletedTravellerId" value="" />
									
									<input type="hidden" id="deletedFile" name="deletedFile" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="clientCode" class="col-lg-4 control-label">Client Code <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="clientCode" name="clientCode" placeholder="Client Code" title="Please enter client code" onblur="checkNameValidation('clients','client_no', this,'<?php echo "client_id##" .$result['vendor']['client_id']; ?>', 'Already exist this client code . Please enter another code.');" value="<?php echo $result['vendor']['client_no']; ?>" readonly="readonly"/>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="address" class="col-lg-4 control-label">Address <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <textarea class="form-control isRequired" name="address" id="address" placeholder="Address" title="Please enter the address"><?php echo str_replace("<br />", '', $result['vendor']['address']); ?></textarea>
                                </div>
                            </div>
                        </div>
					</div>
					
					<div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="gstNo" class="col-lg-4 control-label">GST No. <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="gstNo" name="gstNo" placeholder="GST No" title="Please enter GST number" value="<?php echo $result['vendor']['gst_no']; ?>"/>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                          <div class="form-group">
                              <label for="panNo" class="col-lg-4 control-label">Pan No. <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired" id="panNo" name="panNo" placeholder="Pan number" title="Please enter pan number" value="<?php echo $result['vendor']['client_pan_no']; ?>"/>
                              </div>
                          </div>
                        </div>
                    </div>
					
                    <div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="clientCity" class="col-lg-4 control-label">City <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control isRequired" id="clientCity" name="clientCity" placeholder="Client City" title="Please enter client city" value="<?php echo $result['vendor']['client_city']; ?>"/>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                          <div class="form-group">
                              <label for="pincode" class="col-lg-4 control-label">Pincode <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired" id="pincode" name="pincode" placeholder="Enter pincode" title="Please enter pincode" value="<?php echo $result['vendor']['pin_code']; ?>"/>
                              </div>
                          </div>
                        </div>
                    </div>
					
					<div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTaxType" class="col-lg-4 control-label">Tax Type <span class="mandatory">*</span> </label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" id="serviceTaxType" name="serviceTaxType" title="Please select service tax type" onchange="checkServiceType()">
										<option value="igst" <?php echo(($result['vendor']['service_tax_type']=='igst') ? "selected='selected'" : "") ?>>IGST</option>
                                        <option value="sgst" <?php echo(($result['vendor']['service_tax_type']=='sgst') ? "selected='selected'" : "") ?>>SGST</option>
                                    </select>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                            <div class="form-group" style="margin-left:100px;" id="sgstDiv">
                                <table>
									<tr>
										<td style="width:4%"><label class="col-lg-4 control-label">CGST(%)<span class="mandatory">*</span></label></td>
										<td style="width:12%">
											<input type="text" class="form-control checkNum" id="cgstTax" name="cgstTax" placeholder="CGST" title="Please enter the CGST" value="<?php echo $result['vendor']['cgst_tax']; ?>" />
										</td>
										<td style="width:4%"><label class="col-lg-4 control-label">SGST(%)<span class="mandatory">*</span></label></td>
										<td style="width:26%">
											<input type="text" class="form-control checkNum" id="sgstTax" name="sgstTax" placeholder="SGST" title="Please enter the SGST" value="<?php echo $result['vendor']['sgst_tax']; ?>" style="width:50%"/>
										</td>
									</tr>
								</table>
                            </div>
							<div class="form-group" style="display:none;" id="igstDiv">
                                <label for="igstTax" class="col-lg-4 control-label">IGST (%)</label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control checkNum" id="igstTax" name="igstTax" placeholder="IGST" title="Please enter the IGST" value="<?php echo $result['vendor']['igst_tax']; ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
					<div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Contract Expiry Date <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <input type="text" class="form-control datepicker readonly isRequired" id="contractExpDate" name="contractExpDate" placeholder="Contract Expiry Date" title="Please select contract expiry date" readonly="readonly" value="<?php echo $contExpiryDate; ?>"/>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTaxPaidByClient" class="col-lg-4 control-label">Service Tax Paid By Client <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" id="serviceTaxPaidByClient" name="serviceTaxPaidByClient">
                                        <option value="yes" <?php echo(($result['vendor']['service_tax_paid_by_client']=='yes') ? "selected='selected'" : "") ?>>Yes</option>
                                        <option value="no" <?php echo(($result['vendor']['service_tax_paid_by_client']=='no') ? "selected='selected'" : "") ?>>No</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="serviceTax" class="col-lg-4 control-label">Contract Copy </label>
                                <div class="col-lg-6">
									<?php
									if(isset($result['vendor']['file_name']) && trim($result['vendor']['file_name'])!="" && file_exists($pathname. DIRECTORY_SEPARATOR.$result['vendor']['file_name'])){
									?>
									<div id="fileDiv" style="margin-top:5px;">
									<a target='_blank' href="<?php echo $this->basePath(). DIRECTORY_SEPARATOR."uploads". DIRECTORY_SEPARATOR."clients". DIRECTORY_SEPARATOR .$result['vendor']['client_id']. DIRECTORY_SEPARATOR.$result['vendor']['file_name'] ?>" ><?php echo $result['vendor']['file_name']; ?></a>
									&nbsp;&nbsp;&nbsp;
									<a href="javascript:void(0)" class="btn-sm btn-danger" onclick="deleteAttachment('<?php echo $result['vendor']['file_name']; ?>')"> <i class="fa fa-close"></i> Delete</a>
									</div>
									<?php
									}
									?>
                                    <input type="file" class="form-control" title="please choose file" name="file" id="file">
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
                          <div class="form-group">
                              <label for="stateCode" class="col-lg-4 control-label">State Code <span class="mandatory">*</span></label>
                              <div class="col-lg-6">
                                  <input type="text" class="form-control isRequired checkNum" id="stateCode" name="stateCode" placeholder="Enter state code" title="Please enter state code" value="<?php echo $result['vendor']['client_state_code']; ?>"/>
                              </div>
                          </div>
                        </div>
                    </div>
					<div class="row">
						<div class="col-md-6">
                            <div class="form-group">
                                <label for="status" class="col-lg-4 control-label">Status <span class="mandatory">*</span></label>
                                <div class="col-lg-6">
                                    <select class="form-control isRequired" id="status" name="status" title="Please select status">
                                        <option value="active" <?php echo(($result['vendor']['status']=='active') ? "selected='selected'" : "") ?>>Active</option>
                                        <option value="inactive" <?php echo(($result['vendor']['status']=='inactive') ? "selected='selected'" : "") ?>>Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
					</div>
					
					  
                    <h4>Contact Details</h4>
                    <table id="bookedByTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>Contact Name</th>
                            <th>Phone No</th>
                            <th>Mobile No</th>
							<th>Email</th>
                            <th>Action</th>
                        </tr>
                        </thead>
						<tbody>
						<?php
						$i=1;
						if(sizeof($result['bookedBy'])>0){
							foreach($result['bookedBy'] as $bookedBy){
						?>
							<tr>
								<td>
									<input type="text" id="contactName<?php echo $i;?>" name="contactName[]" class="form-control" placeholder="Contact Name" value="<?php echo $bookedBy['contact_name']; ?>"/>
									<input type="hidden" id="contactId<?php echo $i;?>" name="contactId[]" class="form-control" placeholder="" value="<?php echo $bookedBy['contact_id']; ?>"/>
								</td>
								<td>
									<input type="text" class="form-control" id="phoneNo<?php echo $i;?>" name="phoneNo[]" placeholder="Phone No" title="" value="<?php echo $bookedBy['phone_no']; ?>"/>
								</td>
								<td><input type="text" class="form-control" id="mobileNo<?php echo $i;?>" name="mobileNo[]" placeholder="Mobile No" value="<?php echo $bookedBy['mobile_no']; ?>" /></td>
								<td><input type="text" class="form-control isEmail" id="email<?php echo $i;?>" name="email[]" placeholder="Email" value="<?php echo $bookedBy['email']; ?>" /></td>
								<td align="center">
									<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="<?php echo $bookedBy['contact_id']?>" onclick="removeRow(this.parentNode.parentNode);countDelete(this.id);"><i class="fa fa-minus"></i></a>
								</td>
							</tr>
                        
						<?php
							$i++;
							}
						}else{ ?>
						<tr>
                            <td>
                            <input type="text" id="contactName1" name="contactName[]" class="form-control" placeholder="Contact Name"/>
                            </td>
                            <td>
                            <input type="text" class="form-control" id="phoneNo1" name="phoneNo[]" placeholder="Phone No" title=""/>
                            </td>
                            <td><input type="text" class="form-control" id="mobileNo1" name="mobileNo[]" placeholder="Mobile No" /></td>
							<td><input type="text" class="form-control isEmail" id="email1" name="email[]" placeholder="Email" /></td>
                            <td align="center">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                            </td>
                            
                        </tr>
						<?php } ?>
						</tbody>
                    </table>
                    <!--
                    <h4>Guest Details</h4>
                    <table id="travellerTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>Guest Name</th>
                            <th>Mobile No</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
						<?php
						/*
						$j=1;
						if(sizeof($result['traveller'])>0){
							foreach($result['traveller'] as $traveller){
							*/
						?>
							<tr>
							<td>
								<input type="text" id="travellerName< ?php echo $j; ?>" name="travellerName[]" class="form-control" placeholder="Traveller Name" value="< ?php echo $traveller['guest_name']; ?>"/>
								<input type="hidden" id="passengerId< ?php echo $j;?>" name="passengerId[]" class="form-control" placeholder="" value="< ?php echo $traveller['guest_id']; ?>"/>
							</td>
							<td>
								<input type="text" class="form-control" id="traMobileNo< ?php echo $j; ?>" name="traMobileNo[]" placeholder="Mobile No" value="< ?php echo $traveller['mobile_no']; ?>" />
							</td>
							<td>
								<input type="text" class="form-control isEmail" id="traEmail< ?php echo $j;?>" name="traEmail[]" placeholder="Email" value="< ?php echo $traveller['email']; ?>"/>
							</td>
							<td align="center" style="vertical-align: middle;">
								<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insTravellerRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="< ?php echo $traveller['guest_id']; ?>" onclick="removeTravellerRow(this.parentNode.parentNode);countTravellerDelete(this.id);"><i class="fa fa-minus"></i></a>
							</td>
							
							</tr>
						<?php
						/*
						$j++;
							}
						}else{ */ ?>
						<tr>
                            <td>
                            <input type="text" id="travellerName1" name="travellerName[]" class="form-control" placeholder="Guest Name"/>
                            </td>
                            <td>
                            <input type="text" class="form-control" id="traMobileNo1" name="traMobileNo[]" placeholder="Mobile No" />
                            </td>
                            <td>
                            <input type="text" class="form-control isEmail" id="traEmail1" name="traEmail[]" placeholder="Email" />
                            </td>
                            <td align="center" style="vertical-align: middle;">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insTravellerRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" id="" onclick="removeTravellerRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                            </td>
                            
                        </tr>
						<?php //} ?>
                        </tbody>
                    </table>
                    -->
                    <div class="box-footer">
                        <a href="<?php echo $this->url('clients', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
						<input type="button" class="btn btn-primary" value="Submit" onclick="validateNow();">
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    rowCount='<?php echo $i; ?>';
	traRowCount='1';
	deletedId=[];
	deletedTravellerId=[];
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editVendorInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('editVendorInformation').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
    
    function insRow() {
		rowCount++;
		rl = document.getElementById("bookedByTable").rows.length;
		var a = document.getElementById("bookedByTable").insertRow(rl);
		a.setAttribute("style", "display:none;");
		a.setAttribute("class", "data");
		var b = a.insertCell(0);
		var c = a.insertCell(1);
		var d = a.insertCell(2);
		var e = a.insertCell(3);
		var f= a.insertCell(4);
		
		f.setAttribute("align", "center");
		
		rl = document.getElementById("bookedByTable").rows.length - 1;
		b.innerHTML = '<input type="text" class="form-control" id="contactName' + rowCount + '" name="contactName[]" placeholder="Contact Name" />';
		c.innerHTML = '<input type="text" class="form-control" id="phoneNo' + rowCount + '" name="phoneNo[]" placeholder="Phone No" />';
		d.innerHTML = '<input type="text" class="form-control" id="mobileNo' + rowCount + '" name="mobileNo[]" placeholder="Mobile No"/>';
		e.innerHTML = '<input type="text" class="form-control isEmail" id="email' + rowCount + '" name="email[]" placeholder="Email"/>';
		f.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
		$(a).fadeIn(800);
    }
	
	function removeRow(el) {
		$(el).fadeOut("slow", function() {
		    el.parentNode.removeChild(el);
		    rl = document.getElementById("bookedByTable").rows.length;
		    if (rl == 1) {
			insRow();
		    }
		});
    }
	function insTravellerRow() {
		traRowCount++;
		rl = document.getElementById("travellerTable").rows.length;
		var a = document.getElementById("travellerTable").insertRow(rl);
		a.setAttribute("style", "display:none;");
		a.setAttribute("class", "data");
		var b = a.insertCell(0);
		var c = a.insertCell(1);
		var d = a.insertCell(2);
		var e = a.insertCell(3);
		
		e.setAttribute("align", "center");
		e.setAttribute("style", "vertical-align: middle;");
		
		rl = document.getElementById("travellerTable").rows.length - 1;
		b.innerHTML = '<input type="text" class="form-control" id="travellerName' + traRowCount + '" name="travellerName[]" placeholder="Guest Name" />';
		c.innerHTML = '<input type="text" class="form-control" id="traMobileNo' + traRowCount + '" name="traMobileNo[]" placeholder="Mobile No" />';
		d.innerHTML = '<input type="text" class="form-control isEmail" id="traEmail' + traRowCount + '" name="traEmail[]" placeholder="Email" />';
		e.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insTravellerRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeTravellerRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
		$(a).fadeIn(800);
    }
	
	function removeTravellerRow(el) {
		$(el).fadeOut("slow", function() {
		    el.parentNode.removeChild(el);
		    rl = document.getElementById("travellerTable").rows.length;
		    if (rl == 1) {
			insTravellerRow();
		    }
		});
    }
	function countDelete(e){
		deletedId.push(e);
		document.getElementById("deletedId").value=deletedId;
	}
	function countTravellerDelete(e){
		    deletedTravellerId.push(e);
		    document.getElementById("deletedTravellerId").value=deletedTravellerId;
	}
	
	$(function() {
		$('.datepicker').datepicker({
            //todayBtn: "linked",
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
			format: 'dd-M-yyyy'
		});
		<?php
		if( trim($result['vendor']['file_name'])!="" && file_exists($pathname. DIRECTORY_SEPARATOR.$result['vendor']['file_name'])){
		?>
		$('#file').hide();
		<?php
		}
		?>
		checkServiceType();
	});
	
	function deleteAttachment(fileName) {
	  conf=confirm("Are you sure you want to delete this file");
	  if (conf) {
        $("#deletedFile").val(fileName);
		$('#file').show();
		$('#fileDiv').hide();
      }
    }
	
	function checkServiceType(){
		if($("#serviceTaxType").val()=='sgst'){
			$("#cgstTax").addClass('isRequired');
			$("#sgstTax").addClass('isRequired');
			$("#igstTax").removeClass('isRequired');
			$("#sgstDiv").css('display','block');
			$("#igstDiv").css('display','none');
		}else{
			$("#sgstDiv").css('display','none');
			$("#igstDiv").css('display','block');
			$("#cgstTax").removeClass('isRequired');
			$("#sgstTax").removeClass('isRequired');
			$("#igstTax").addClass('isRequired');
		}
	}
</script>