<?php
use Application\Service\CommonService;
$commonService=new CommonService();
$contExpiryDate="";
$pathname = UPLOAD_PATH . DIRECTORY_SEPARATOR . "clients" . DIRECTORY_SEPARATOR .$result['vendor']['client_id'];
if(isset($result['vendor']['contract_exp_date']) && trim($result['vendor']['contract_exp_date'])!=""){
	$contExpiryDate=$commonService->humanDateFormat($result['vendor']['contract_exp_date']);
}
//\Zend\Debug\Debug::dump($result);die;
?>
<!-- Main content -->
<div class="content-wrapper">
     <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>View Client</h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('clients', array('action' => 'index')); ?>"> Clients</a></li>
        <li class="active">View Client</li>
      </ol>
    </section>
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="editVendorInformation" id="editVendorInformation"  method="post" action="<?php echo $this->url('clients', array('action' => 'edit')); ?>" enctype="multipart/form-data" autocomplete="off">
                <div class="box-body">
					<table class="table table-striped table-bordered table-condensed" align="center" style="width: 70%;">
						<thead>
                        <tr>
                            <th colspan="2" style="text-align: center;" class="bg-aqua">Client Details</th>
                        </tr>
                        </thead>
						<tr>
							<th style="width: 20%;">Company</th>
							<td><?php echo $result['vendor']['company_name']; ?></td>
						</tr>
						<tr>
							<th>Client Name</th>
							<td><?php echo $result['vendor']['client_name']; ?></td>
						</tr>
						<tr>
							<th>Client Code</th>
							<td><?php echo $result['vendor']['client_no']; ?></td>
						</tr>
						<tr>
							<th>Address</th>
							<td><?php echo str_replace("<br />", '', $result['vendor']['address']); ?></td>
						</tr>
						<tr>
							<th>City</th>
							<td><?php echo $result['vendor']['client_city']; ?></td>
						</tr>
						<tr>
							<th>Pincode</th>
							<td><?php echo $result['vendor']['pin_code']; ?></td>
						</tr>
						<tr>
							<th>Service Tax Type</th>
							<td><?php echo strtoupper($result['vendor']['service_tax_type']); ?></td>
						</tr>
						<?php
						if(isset($result['vendor']['service_tax_type']) && trim($result['vendor']['service_tax_type'])=="sgst"){
						?>
						<tr>
							<th>CGST (%)</th>
							<td><?php echo $result['vendor']['cgst_tax']; ?></td>
						</tr>
						<tr>
							<th>SGST (%)</th>
							<td><?php echo $result['vendor']['sgst_tax']; ?></td>
						</tr>
						<?php
						}
						else if(isset($result['vendor']['service_tax_type']) && trim($result['vendor']['service_tax_type'])=="sgst"){
						?>
						<tr>
							<th>IGST (%)</th>
							<td><?php echo $result['vendor']['igst_tax']; ?></td>
						</tr>
						<?php
						}
						?>
						<tr>
							<th>Contract Expiry Date</th>
							<td>
								<?php
									if(isset($result['vendor']['file_name']) && trim($result['vendor']['file_name'])!="" && file_exists($pathname. DIRECTORY_SEPARATOR.$result['vendor']['file_name'])){
									?>
									<div id="fileDiv" style="margin-top:5px;">
									<a target='_blank' href="<?php echo $this->basePath(). DIRECTORY_SEPARATOR."uploads". DIRECTORY_SEPARATOR."clients". DIRECTORY_SEPARATOR .$result['vendor']['client_id']. DIRECTORY_SEPARATOR.$result['vendor']['file_name'] ?>" ><?php echo $result['vendor']['file_name']; ?></a>
									</div>
									<?php
									}
								?>
							</td>
						</tr>
						<tr>
							<th>Service Tax Paid By Client </th>
							<td><?php echo ucwords($result['vendor']['service_tax_paid_by_client']); ?></td>
						</tr>
						<tr>
							<th>Status</th>
							<td><?php echo ucwords($result['vendor']['status']); ?></td>
						</tr>
						
					</table>
					<br/>
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" align="center" style="width: 70%;">
                        <thead>
							<tr>
								<th colspan="4" style="text-align: center;" class="bg-aqua">Contact Details</th>
							</tr>
							<tr>
								<th>Contact Name</th>
								<th>Phone No</th>
								<th>Mobile No</th>
								<th>Email</th>
							</tr>
                        </thead>
						<tbody>
						<?php
						if(sizeof($result['bookedBy'])>0){
							foreach($result['bookedBy'] as $bookedBy){
						?>
							<tr>
								<td>
									<?php echo $bookedBy['contact_name']; ?>
								</td>
								<td>
									<?php echo $bookedBy['phone_no']; ?>
								</td>
								<td><?php echo $bookedBy['mobile_no']; ?></td>
								<td><?php echo $bookedBy['email']; ?></td>
							</tr>
						<?php
							}
						}else{ ?>
						<tr>
                            <td colspan="4">
                            No data available
                            </td>
                        </tr>
						<?php } ?>
						</tbody>
                    </table>
                    
                    <div class="box-footer">
                        <a href="<?php echo $this->url('clients', array('action' => 'index')); ?>" class="btn btn-default">Back</a>
                    </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->
    </div>

<script type="text/javascript">
   
</script>