<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->employeeCode;
//\Zend\Debug\Debug::dump($renewalResult);die;
?>
<!-- Content Header (Page header) -->
    <section class="content-header">
		<div class="row" id="pageHeading">
			<div class="col-xs-6" style="font-size:25px;">
				<span class="pageHeadingLabel1" >Operations </span>
				<span class="pageHeadingLabe12"> Dashboard</span>
			</div>
			<div class="col-xs-6">
				<span class="pull-right">
					
				</span>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 col-sm-6 col-xs-12">
				<div class="info-box" >
					<span class="info-box-number"><?php echo $todayCurrentBooking; ?></span>
					<span class="info-box-text">CURRENT BOOKING</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12">
				<div class="info-box">
					<span class="info-box-number"><?php echo $todayExecutedBooking; ?></span>
					<span class="info-box-text">EXECUTED BOOKING</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12">
				<div class="info-box">
					<span class="info-box-number cancel-booking-count"><?php echo $todayCanceledBooking; ?></span>
					<span class="info-box-text">CANCELLED BOOKING</span>
				</div>
			</div>
		</div>
    </section>
	
    <!-- Main content -->
    <section class="content">
      <div class="row">
		<!-- Pending Work Order Start-->
			<div class="col-md-6">
			<div class="box" >
				<div class="box-header with-border">
					<h3 class="box-title"><i class="fa fa-calendar"></i>Pending Work Orders</h3>
					<div class="box-tools pull-right">
					  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					</div>
				</div>
				<div class="box-body chart-responsive" style="min-height:600px;">
					<table id="pendingWorkOrderTable" class="beecabsTable table">
						<thead>
							<tr>
								<th>Work Order No</th>
								<th>Vehicle No</th>
								<th>Garage Name</th>
								<th>Garage In Date</th>
								<th>Garage In Kms</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td colspan="7" class="dataTables_empty">Loading data from server</td>
							</tr>
						</tbody>
					</table>
				</div>
			  <!-- /.box-body -->
			</div>
			<!-- /.box -->
			</div>
			<!-- Pending Work Order End-->
        <!-- /.col (LEFT) -->
        <div class="col-md-6">
          <div class="box" >
            <div class="box-header with-border">
              <h3 class="box-title"><i class="fa fa-file-code-o"></i>Client Contract Expiry</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>
            </div>
            <div class="box-body chart-responsive" style="min-height:600px;">
				<table id="clientDataTable" class="beecabsTable table">
					<thead>
						<tr>
							<th>Client Name</th>
							<th>Contract Expiry Date</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							  <td colspan="3" class="dataTables_empty">Loading data from server</td>
						</tr>
					</tbody>
				</table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col (RIGHT) -->
      </div>
      <!-- /.row -->

		<div class="row">
			<div class="col-md-6">
				<!-- DONUT CHART -->
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Vehicle Renewals</h3>
		
						<div class="box-tools pull-right">
						  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						</div>
					</div>
					<div class="box-body chart-responsive">
					  <div class="chart" id="sales-chart" style="height: 400px;max-width:600px;margin:0 auto; position: relative;"></div>
					</div>
				<!-- /.box-body -->
				</div>
			<!-- /.box -->
			</div>
			
			<div class="col-md-6">
				<!-- DONUT CHART -->
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Employee Document Expiry</h3>
		
						<div class="box-tools pull-right">
						  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						</div>
					</div>
					<div class="box-body chart-responsive">
					  <div class="chart" id="employeeLicenseExpiry" style="height: 400px;max-width:600px;margin:0 auto; position: relative;"></div>
					</div>
				<!-- /.box-body -->
				</div>
			<!-- /.box -->
			</div>
			
		</div>
		
    </section>
<!-- page script -->
<script src="<?php echo $this->basePath() . '/assets/plugins/highcharts/code/highcharts.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/plugins/highcharts/code/modules/exporting.js' ?>"></script>
<script type="text/javascript">
	oTable = null;
	$(document).ready(function() {
		$('#clientDataTable').dataTable( {
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			 "aoColumns": [
				{"sClass":"center"},
				{"sClass":"center"}
				],
			"sAjaxSource": "<?php echo $this->url('clients',array('action' => 'contract-expiry')); ?>",
			"fnServerData": function ( sSource, aoData, fnCallback ) {
					$.ajax({
						"dataType": 'json',
						"type": "POST",
						"url": sSource,
						"data": aoData,
						"success": fnCallback
					});
				}
		} );	
		
		oTable=$('#pendingWorkOrderTable').dataTable({
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			 "aoColumns": [
				{"sClass":"center"},
				{"sClass":"center"},
				{"sClass":"center"},
				{"sClass":"center"},
				{"sClass":"center"},
				{"sClass":"center"}
				],
			"aaSorting": [[3, "desc"]],
			"sAjaxSource": "<?php echo $this->url('vehicle-service',array('action' => 'pending-work-order')); ?>",
			 "fnServerData": function ( sSource, aoData, fnCallback ) {
					$.ajax({
						"dataType": 'json',
						"type": "POST",
						"url": sSource,
						"data": aoData,
						"success": fnCallback
					});
				}
		});
	
	//Renewal result
	Highcharts.chart('sales-chart', {
		chart: {
			plotBackgroundColor: null,
			plotBorderWidth: null,
			plotShadow: false,
			type: 'pie'
		},
		title: {
			text: ''
		},
		plotOptions: {
			pie: {
				size: 250,
				borderColor: 'white',
				innerSize: '60%',
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					format: '<b>{point.name}</b><br>{point.y}',
				},
				showInLegend: true,
				colors: [
				'#215682',
				'#da0d0d',
				'#24CBE5',
				'#989898',
				'#cecece'
				]
			}
		},
		credits: {
		enabled: false
		},
		series: [{
			name: 'Total',
			colorByPoint: true,
			 data: [
				<?php
				foreach($renewalResult as $key=>$val){
					?>
					{name:'<?php echo ucwords($key);?>',y:<?php echo $val;?>},
					<?php
				}
				?>
				]
		}]
	});
	
	//Employee License Expiry result
	Highcharts.chart('employeeLicenseExpiry', {
		chart: {
			plotBackgroundColor: null,
			plotBorderWidth: null,
			plotShadow: false,
			type: 'pie'
		},
		title: {
			text: ''
		},
		tooltip: {
			pointFormat: '{series.name}: <b>{point.y:.1f}</b>'
		},
		plotOptions: {
			pie: {
				size: 250,
				borderColor: 'white',
				innerSize: '60%',
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					format: '<b>{point.name}</b><br>{point.y}',
				},
				showInLegend: true,
				colors: [
				'#215682',
				'#bfbfbf'
				]
			}
		},
		credits: {
		enabled: false
		},
		series: [{
			name: 'Total',
			colorByPoint: true,
			 data: [
					{name:'License Expiry',y:<?php echo $employeeExpiryResult['licenseCount'];?>},
					{name:'Badge Expiry',y:<?php echo $employeeExpiryResult['badgeCount'];?>},
				]
		}]
	});
	
  });
</script>
